// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: process/v1/process.proto

package process

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signal int32

const (
	Signal_SIGNAL_UNSPECIFIED Signal = 0
	Signal_SIGNAL_SIGINT      Signal = 2
	Signal_SIGNAL_SIGKILL     Signal = 9
	Signal_SIGNAL_SIGTERM     Signal = 15
)

// Enum value maps for Signal.
var (
	Signal_name = map[int32]string{
		0:  "SIGNAL_UNSPECIFIED",
		2:  "SIGNAL_SIGINT",
		9:  "SIGNAL_SIGKILL",
		15: "SIGNAL_SIGTERM",
	}
	Signal_value = map[string]int32{
		"SIGNAL_UNSPECIFIED": 0,
		"SIGNAL_SIGINT":      2,
		"SIGNAL_SIGKILL":     9,
		"SIGNAL_SIGTERM":     15,
	}
)

func (x Signal) Enum() *Signal {
	p := new(Signal)
	*p = x
	return p
}

func (x Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_process_v1_process_proto_enumTypes[0].Descriptor()
}

func (Signal) Type() protoreflect.EnumType {
	return &file_process_v1_process_proto_enumTypes[0]
}

func (x Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal.Descriptor instead.
func (Signal) EnumDescriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{0}
}

type PTY struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTY) Reset() {
	*x = PTY{}
	mi := &file_process_v1_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTY) ProtoMessage() {}

func (x *PTY) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTY.ProtoReflect.Descriptor instead.
func (*PTY) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{0}
}

func (x *PTY) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTY) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ProcessConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,2,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           *string                `protobuf:"bytes,3,opt,name=cwd,proto3,oneof" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessConfig) Reset() {
	*x = ProcessConfig{}
	mi := &file_process_v1_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessConfig) ProtoMessage() {}

func (x *ProcessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessConfig.ProtoReflect.Descriptor instead.
func (*ProcessConfig) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessConfig) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProcessConfig) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *ProcessConfig) GetCwd() string {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ProcessConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Pty           *PTY                   `protobuf:"bytes,2,opt,name=pty,proto3,oneof" json:"pty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_process_v1_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetConfig() *ProcessConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StartRequest) GetPty() *PTY {
	if x != nil {
		return x.Pty
	}
	return nil
}

type ProcessInitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int32                  `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInitEvent) Reset() {
	*x = ProcessInitEvent{}
	mi := &file_process_v1_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInitEvent) ProtoMessage() {}

func (x *ProcessInitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInitEvent.ProtoReflect.Descriptor instead.
func (*ProcessInitEvent) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessInitEvent) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

type ExitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitEvent) Reset() {
	*x = ExitEvent{}
	mi := &file_process_v1_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitEvent) ProtoMessage() {}

func (x *ExitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitEvent.ProtoReflect.Descriptor instead.
func (*ExitEvent) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{4}
}

func (x *ExitEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type StreamOutputResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamOutputResponse_Init
	//	*StreamOutputResponse_Stdout
	//	*StreamOutputResponse_Stderr
	//	*StreamOutputResponse_Exit
	Event         isStreamOutputResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputResponse) Reset() {
	*x = StreamOutputResponse{}
	mi := &file_process_v1_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputResponse) ProtoMessage() {}

func (x *StreamOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputResponse.ProtoReflect.Descriptor instead.
func (*StreamOutputResponse) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{5}
}

func (x *StreamOutputResponse) GetEvent() isStreamOutputResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamOutputResponse) GetInit() *ProcessInitEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamOutputResponse_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *StreamOutputResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Event.(*StreamOutputResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *StreamOutputResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Event.(*StreamOutputResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *StreamOutputResponse) GetExit() *ExitEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamOutputResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isStreamOutputResponse_Event interface {
	isStreamOutputResponse_Event()
}

type StreamOutputResponse_Init struct {
	Init *ProcessInitEvent `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type StreamOutputResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type StreamOutputResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

type StreamOutputResponse_Exit struct {
	Exit *ExitEvent `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

func (*StreamOutputResponse_Init) isStreamOutputResponse_Event() {}

func (*StreamOutputResponse_Stdout) isStreamOutputResponse_Event() {}

func (*StreamOutputResponse_Stderr) isStreamOutputResponse_Event() {}

func (*StreamOutputResponse_Exit) isStreamOutputResponse_Event() {}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ProcessConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_process_v1_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteRequest) GetConfig() *ProcessConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_process_v1_process_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecuteResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

type WriteStdinRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId int32                  `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WriteStdinRequest_Input
	//	*WriteStdinRequest_Eof
	Payload       isWriteStdinRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinRequest) Reset() {
	*x = WriteStdinRequest{}
	mi := &file_process_v1_process_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinRequest) ProtoMessage() {}

func (x *WriteStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinRequest.ProtoReflect.Descriptor instead.
func (*WriteStdinRequest) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{8}
}

func (x *WriteStdinRequest) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *WriteStdinRequest) GetPayload() isWriteStdinRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteStdinRequest) GetInput() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WriteStdinRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *WriteStdinRequest) GetEof() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Payload.(*WriteStdinRequest_Eof); ok {
			return x.Eof
		}
	}
	return nil
}

type isWriteStdinRequest_Payload interface {
	isWriteStdinRequest_Payload()
}

type WriteStdinRequest_Input struct {
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type WriteStdinRequest_Eof struct {
	Eof *emptypb.Empty `protobuf:"bytes,3,opt,name=eof,proto3,oneof"`
}

func (*WriteStdinRequest_Input) isWriteStdinRequest_Payload() {}

func (*WriteStdinRequest_Eof) isWriteStdinRequest_Payload() {}

type SendSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int32                  `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Signal        Signal                 `protobuf:"varint,2,opt,name=signal,proto3,enum=process.v1.Signal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSignalRequest) Reset() {
	*x = SendSignalRequest{}
	mi := &file_process_v1_process_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSignalRequest) ProtoMessage() {}

func (x *SendSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSignalRequest.ProtoReflect.Descriptor instead.
func (*SendSignalRequest) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{9}
}

func (x *SendSignalRequest) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *SendSignalRequest) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_SIGNAL_UNSPECIFIED
}

type ResizeTTYRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int32                  `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTTYRequest) Reset() {
	*x = ResizeTTYRequest{}
	mi := &file_process_v1_process_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTTYRequest) ProtoMessage() {}

func (x *ResizeTTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_v1_process_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTTYRequest.ProtoReflect.Descriptor instead.
func (*ResizeTTYRequest) Descriptor() ([]byte, []int) {
	return file_process_v1_process_proto_rawDescGZIP(), []int{10}
}

func (x *ResizeTTYRequest) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *ResizeTTYRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizeTTYRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

var File_process_v1_process_proto protoreflect.FileDescriptor

const file_process_v1_process_proto_rawDesc = "" +
	"\n" +
	"\x18process/v1/process.proto\x12\n" +
	"process.v1\x1a\x1bgoogle/protobuf/empty.proto\"-\n" +
	"\x03PTY\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\xc7\x01\n" +
	"\rProcessConfig\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12A\n" +
	"\benv_vars\x18\x02 \x03(\v2&.process.v1.ProcessConfig.EnvVarsEntryR\aenvVars\x12\x15\n" +
	"\x03cwd\x18\x03 \x01(\tH\x00R\x03cwd\x88\x01\x01\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_cwd\"q\n" +
	"\fStartRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.process.v1.ProcessConfigR\x06config\x12&\n" +
	"\x03pty\x18\x02 \x01(\v2\x0f.process.v1.PTYH\x00R\x03pty\x88\x01\x01B\x06\n" +
	"\x04_pty\"1\n" +
	"\x10ProcessInitEvent\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x05R\tprocessId\"(\n" +
	"\tExitEvent\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"\xb4\x01\n" +
	"\x14StreamOutputResponse\x122\n" +
	"\x04init\x18\x01 \x01(\v2\x1c.process.v1.ProcessInitEventH\x00R\x04init\x12\x18\n" +
	"\x06stdout\x18\x02 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x03 \x01(\fH\x00R\x06stderr\x12+\n" +
	"\x04exit\x18\x04 \x01(\v2\x15.process.v1.ExitEventH\x00R\x04exitB\a\n" +
	"\x05event\"C\n" +
	"\x0eExecuteRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.process.v1.ProcessConfigR\x06config\"^\n" +
	"\x0fExecuteResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\"\x81\x01\n" +
	"\x11WriteStdinRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x05R\tprocessId\x12\x16\n" +
	"\x05input\x18\x02 \x01(\fH\x00R\x05input\x12*\n" +
	"\x03eof\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x03eofB\t\n" +
	"\apayload\"^\n" +
	"\x11SendSignalRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x05R\tprocessId\x12*\n" +
	"\x06signal\x18\x02 \x01(\x0e2\x12.process.v1.SignalR\x06signal\"Y\n" +
	"\x10ResizeTTYRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x05R\tprocessId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows*[\n" +
	"\x06Signal\x12\x16\n" +
	"\x12SIGNAL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSIGNAL_SIGINT\x10\x02\x12\x12\n" +
	"\x0eSIGNAL_SIGKILL\x10\t\x12\x12\n" +
	"\x0eSIGNAL_SIGTERM\x10\x0f2\xe1\x02\n" +
	"\aProcess\x12E\n" +
	"\x05Start\x12\x18.process.v1.StartRequest\x1a .process.v1.StreamOutputResponse0\x01\x12B\n" +
	"\aExecute\x12\x1a.process.v1.ExecuteRequest\x1a\x1b.process.v1.ExecuteResponse\x12C\n" +
	"\n" +
	"WriteStdin\x12\x1d.process.v1.WriteStdinRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"SendSignal\x12\x1d.process.v1.SendSignalRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\tResizeTTY\x12\x1c.process.v1.ResizeTTYRequest\x1a\x16.google.protobuf.EmptyBp\n" +
	"*io.sandboxd.packages.sandboxd.spec.processP\x01Z@sigs.k8s.io/agent-sandbox/packages/sandboxd/spec/process;processb\x06proto3"

var (
	file_process_v1_process_proto_rawDescOnce sync.Once
	file_process_v1_process_proto_rawDescData []byte
)

func file_process_v1_process_proto_rawDescGZIP() []byte {
	file_process_v1_process_proto_rawDescOnce.Do(func() {
		file_process_v1_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_process_v1_process_proto_rawDesc), len(file_process_v1_process_proto_rawDesc)))
	})
	return file_process_v1_process_proto_rawDescData
}

var file_process_v1_process_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_process_v1_process_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_process_v1_process_proto_goTypes = []any{
	(Signal)(0),                  // 0: process.v1.Signal
	(*PTY)(nil),                  // 1: process.v1.PTY
	(*ProcessConfig)(nil),        // 2: process.v1.ProcessConfig
	(*StartRequest)(nil),         // 3: process.v1.StartRequest
	(*ProcessInitEvent)(nil),     // 4: process.v1.ProcessInitEvent
	(*ExitEvent)(nil),            // 5: process.v1.ExitEvent
	(*StreamOutputResponse)(nil), // 6: process.v1.StreamOutputResponse
	(*ExecuteRequest)(nil),       // 7: process.v1.ExecuteRequest
	(*ExecuteResponse)(nil),      // 8: process.v1.ExecuteResponse
	(*WriteStdinRequest)(nil),    // 9: process.v1.WriteStdinRequest
	(*SendSignalRequest)(nil),    // 10: process.v1.SendSignalRequest
	(*ResizeTTYRequest)(nil),     // 11: process.v1.ResizeTTYRequest
	nil,                          // 12: process.v1.ProcessConfig.EnvVarsEntry
	(*emptypb.Empty)(nil),        // 13: google.protobuf.Empty
}
var file_process_v1_process_proto_depIdxs = []int32{
	12, // 0: process.v1.ProcessConfig.env_vars:type_name -> process.v1.ProcessConfig.EnvVarsEntry
	2,  // 1: process.v1.StartRequest.config:type_name -> process.v1.ProcessConfig
	1,  // 2: process.v1.StartRequest.pty:type_name -> process.v1.PTY
	4,  // 3: process.v1.StreamOutputResponse.init:type_name -> process.v1.ProcessInitEvent
	5,  // 4: process.v1.StreamOutputResponse.exit:type_name -> process.v1.ExitEvent
	2,  // 5: process.v1.ExecuteRequest.config:type_name -> process.v1.ProcessConfig
	13, // 6: process.v1.WriteStdinRequest.eof:type_name -> google.protobuf.Empty
	0,  // 7: process.v1.SendSignalRequest.signal:type_name -> process.v1.Signal
	3,  // 8: process.v1.Process.Start:input_type -> process.v1.StartRequest
	7,  // 9: process.v1.Process.Execute:input_type -> process.v1.ExecuteRequest
	9,  // 10: process.v1.Process.WriteStdin:input_type -> process.v1.WriteStdinRequest
	10, // 11: process.v1.Process.SendSignal:input_type -> process.v1.SendSignalRequest
	11, // 12: process.v1.Process.ResizeTTY:input_type -> process.v1.ResizeTTYRequest
	6,  // 13: process.v1.Process.Start:output_type -> process.v1.StreamOutputResponse
	8,  // 14: process.v1.Process.Execute:output_type -> process.v1.ExecuteResponse
	13, // 15: process.v1.Process.WriteStdin:output_type -> google.protobuf.Empty
	13, // 16: process.v1.Process.SendSignal:output_type -> google.protobuf.Empty
	13, // 17: process.v1.Process.ResizeTTY:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_process_v1_process_proto_init() }
func file_process_v1_process_proto_init() {
	if File_process_v1_process_proto != nil {
		return
	}
	file_process_v1_process_proto_msgTypes[1].OneofWrappers = []any{}
	file_process_v1_process_proto_msgTypes[2].OneofWrappers = []any{}
	file_process_v1_process_proto_msgTypes[5].OneofWrappers = []any{
		(*StreamOutputResponse_Init)(nil),
		(*StreamOutputResponse_Stdout)(nil),
		(*StreamOutputResponse_Stderr)(nil),
		(*StreamOutputResponse_Exit)(nil),
	}
	file_process_v1_process_proto_msgTypes[8].OneofWrappers = []any{
		(*WriteStdinRequest_Input)(nil),
		(*WriteStdinRequest_Eof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_process_v1_process_proto_rawDesc), len(file_process_v1_process_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_process_v1_process_proto_goTypes,
		DependencyIndexes: file_process_v1_process_proto_depIdxs,
		EnumInfos:         file_process_v1_process_proto_enumTypes,
		MessageInfos:      file_process_v1_process_proto_msgTypes,
	}.Build()
	File_process_v1_process_proto = out.File
	file_process_v1_process_proto_goTypes = nil
	file_process_v1_process_proto_depIdxs = nil
}
