// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agentsandbox/worker/v1/worker.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Ping_FullMethodName      = "/agentsandbox.worker.v1.WorkerService/Ping"
	WorkerService_Exec_FullMethodName      = "/agentsandbox.worker.v1.WorkerService/Exec"
	WorkerService_OpenShell_FullMethodName = "/agentsandbox.worker.v1.WorkerService/OpenShell"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService runs inside the bubblewrap sandbox. It is exposed only
// over the per-tenant Unix socket bind-mounted into the sandbox by the
// pod-agent; nothing outside the sandbox needs this API.
//
// The pod-agent is the sole client. End users do not talk to this API
// directly — they hit the pod-agent's HTTP/SSH proxy which translates to
// the worker.
type WorkerServiceClient interface {
	// Ping is a cheap liveness check. Worker returns its own pid and start
	// time so the pod-agent can detect a worker restart inside an otherwise
	// healthy-looking sandbox.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Exec runs a command inside the sandbox and streams its stdout/stderr.
	// The final stream message carries the exit status. Stdin is not yet
	// supported; that will be added when SSH lands.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error)
	// OpenShell starts an interactive shell inside the sandbox under a
	// freshly-allocated PTY. The client sends Start exactly once as the
	// first frame, then Stdin/Resize/Eof frames; the server streams
	// Stdout/Stderr/Exit. Used by the pod-agent's SSH server.
	OpenShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenShellRequest, OpenShellResponse], error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, WorkerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_ExecClient = grpc.ServerStreamingClient[ExecResponse]

func (c *workerServiceClient) OpenShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenShellRequest, OpenShellResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[1], WorkerService_OpenShell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenShellRequest, OpenShellResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_OpenShellClient = grpc.BidiStreamingClient[OpenShellRequest, OpenShellResponse]

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService runs inside the bubblewrap sandbox. It is exposed only
// over the per-tenant Unix socket bind-mounted into the sandbox by the
// pod-agent; nothing outside the sandbox needs this API.
//
// The pod-agent is the sole client. End users do not talk to this API
// directly — they hit the pod-agent's HTTP/SSH proxy which translates to
// the worker.
type WorkerServiceServer interface {
	// Ping is a cheap liveness check. Worker returns its own pid and start
	// time so the pod-agent can detect a worker restart inside an otherwise
	// healthy-looking sandbox.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Exec runs a command inside the sandbox and streams its stdout/stderr.
	// The final stream message carries the exit status. Stdin is not yet
	// supported; that will be added when SSH lands.
	Exec(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error
	// OpenShell starts an interactive shell inside the sandbox under a
	// freshly-allocated PTY. The client sends Start exactly once as the
	// first frame, then Stdin/Resize/Eof frames; the server streams
	// Stdout/Stderr/Exit. Used by the pod-agent's SSH server.
	OpenShell(grpc.BidiStreamingServer[OpenShellRequest, OpenShellResponse]) error
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWorkerServiceServer) Exec(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedWorkerServiceServer) OpenShell(grpc.BidiStreamingServer[OpenShellRequest, OpenShellResponse]) error {
	return status.Errorf(codes.Unimplemented, "method OpenShell not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).Exec(m, &grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_ExecServer = grpc.ServerStreamingServer[ExecResponse]

func _WorkerService_OpenShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).OpenShell(&grpc.GenericServerStream[OpenShellRequest, OpenShellResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_OpenShellServer = grpc.BidiStreamingServer[OpenShellRequest, OpenShellResponse]

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentsandbox.worker.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _WorkerService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _WorkerService_Exec_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OpenShell",
			Handler:       _WorkerService_OpenShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentsandbox/worker/v1/worker.proto",
}
