apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: sandbox-example
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: sandbox-example
    spec:
      containers:
        - name: devcontainer-main
          image: ghcr.io/coder/envbuilder
          env:
            # URL to the repository where the .devcontainer folder we want to load is located
            # for a branch append "#refs/heads/branch-name"
            - name: ENVBUILDER_GIT_URL
              value: "https://github.com/kubernetes-sigs/agent-sandbox.git"
            - name: ENVBUILDER_DEVCONTAINER_DIR
              value: "examples/vscode-sandbox"
            - name: ENVBUILDER_GIT_CLONE_SINGLE_BRANCH
              value: "true"
            - name: ENVBUILDER_INIT_SCRIPT
              value: "examples/vscode-sandbox/entrypoint.sh"
            - name: AGENT_PROMPT
              value: "You are an expert kubernetes developer who is helping with code reviews. Please look at the most recent commit and provide a review feedback. Dont make any code changes. Would you approve it ?"
            - name: ENVBUILDER_IGNORE_PATHS
              value: "/var/run,/product_uuid,/product_name,/tokens"
          volumeMounts:
            - mountPath: /workspaces
              name: workspaces-pvc
  volumeClaimTemplates:
    - metadata:
        name: workspaces-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
