apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: aio-sandbox-example
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: aio-sandbox-example
    spec:
      containers:
        - name: aio-sandbox
          image: ghcr.io/agent-infra/sandbox:latest
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"

