apiVersion: agents.x-k8s.io/v1beta1
kind: Sandbox
metadata:
  name: demo
spec:
  podTemplate:
    spec:
      containers:
      - name: my-container
        image: kind.local/agent-sandbox-demo-app:latest
      restartPolicy: Never
