// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apiv1alpha1 "sigs.k8s.io/agent-sandbox/extensions/api/v1alpha1"
)

// ManagedSandboxLister helps list ManagedSandboxes.
// All objects returned here must be treated as read-only.
type ManagedSandboxLister interface {
	// List lists all ManagedSandboxes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ManagedSandbox, err error)
	// ManagedSandboxes returns an object that can list and get ManagedSandboxes.
	ManagedSandboxes(namespace string) ManagedSandboxNamespaceLister
	ManagedSandboxListerExpansion
}

// managedSandboxLister implements the ManagedSandboxLister interface.
type managedSandboxLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ManagedSandbox]
}

// NewManagedSandboxLister returns a new ManagedSandboxLister.
func NewManagedSandboxLister(indexer cache.Indexer) ManagedSandboxLister {
	return &managedSandboxLister{listers.New[*apiv1alpha1.ManagedSandbox](indexer, apiv1alpha1.Resource("managedsandbox"))}
}

// ManagedSandboxes returns an object that can list and get ManagedSandboxes.
func (s *managedSandboxLister) ManagedSandboxes(namespace string) ManagedSandboxNamespaceLister {
	return managedSandboxNamespaceLister{listers.NewNamespaced[*apiv1alpha1.ManagedSandbox](s.ResourceIndexer, namespace)}
}

// ManagedSandboxNamespaceLister helps list and get ManagedSandboxes.
// All objects returned here must be treated as read-only.
type ManagedSandboxNamespaceLister interface {
	// List lists all ManagedSandboxes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ManagedSandbox, err error)
	// Get retrieves the ManagedSandbox from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.ManagedSandbox, error)
	ManagedSandboxNamespaceListerExpansion
}

// managedSandboxNamespaceLister implements the ManagedSandboxNamespaceLister
// interface.
type managedSandboxNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ManagedSandbox]
}
