version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    gomod-dependencies:
      patterns:
      - "*"

- package-ecosystem: "gomod"
  directory: "/dev/tools"
  schedule:
    interval: "weekly"
  groups:
    gomod-dependencies:
      patterns:
      - "*"

- package-ecosystem: "gomod"
  directory: "/examples/chrome-sandbox"
  schedule:
    interval: "weekly"
  groups:
    gomod-dependencies:
      patterns:
      - "*"

- package-ecosystem: "gomod"
  directory: "/site"
  schedule:
    interval: "weekly"
  groups:
    gomod-dependencies:
      patterns:
      - "*"

- package-ecosystem: "pip"
  directory: "/clients/python/agentic-sandbox-client"
  schedule:
    interval: "weekly"
  groups:
    python-dependencies:
      patterns:
      - "*"

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/clients/python/agentic-sandbox-client/sandbox-router"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/examples/chrome-sandbox"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/examples/gemini-cu-sandbox"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/examples/hello-world-sandbox"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/examples/python-runtime-sandbox"
  schedule:
    interval: "weekly"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      patterns:
      - "*"
