# Check the documentation at https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

# Prepare files for the release
before:
  hooks:
    - go mod tidy
    # Ensures k8s/ manifests are up-to-date
    - go generate ./...
    # Prepares the final release manifests
    - |
      sh -c "
        set -e;
        mkdir -p release_assets;
        
        # All .yaml files within the k8s/ directory that DO NOT start with 'extensions' are core.
        echo 'INFO: Preparing core manifest.yaml';
        find k8s -type f -name '*.yaml' -and -not -name 'extensions*' | xargs cat > ./release_assets/manifest.yaml;

        # Construct the image URL using the Git tag.
        # Note: this requires the image to have been promoted staging manually, after the Git tag is created.
        IMAGE_URL='registry.k8s.io/agent-sandbox/agent-sandbox-controller:{{.Tag}}';

        echo 'INFO: Replacing image placeholder in core manifest.yaml with: $IMAGE_URL';
        sed -i 's|ko://sigs.k8s.io/agent-sandbox/cmd/agent-sandbox-controller.*|'$IMAGE_URL'|' ./release_assets/manifest.yaml;
        echo 'INFO: Successfully created release_assets/manifest.yaml';

        # All .yaml files within the k8s/ directory that start with 'extensions' are extensions.
        echo 'INFO: Preparing extensions.yaml';
        find k8s -type f -name 'extensions*.yaml' | xargs cat > ./release_assets/extensions.yaml;
        echo 'INFO: Successfully created release_assets/extensions.yaml';
      "

# Skipping the build step, as images are built and promoted separately.
builds:
  - skip: true

release:
  github:
    owner: kubernetes-sigs
    name: agent-sandbox

  # Create a draft release for manual verification before publishing.
  draft: true

  # Automatically mark releases from tags like 'v0.1.0-rc.1' as a "Pre-release".
  prerelease: auto

  # GoReleaser will find these files (prepared by the 'before' hook)
  # and attach them as assets to the GitHub Release.
  extra_files:
    - glob: ./release_assets/manifest.yaml
      name_template: "manifest.yaml"
    - glob: ./release_assets/extensions.yaml
      name_template: "extensions.yaml"

changelog:
  sort: asc
  filters:
    exclude:
      # Excludes commits that start with 'docs:' or 'test:'
      - '^docs:'
      - '^test:'