apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-sandbox-config
  namespace: {{ include "agent-sandbox.namespace" . }}
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.controllerConfig }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
