apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-sandbox-config
  namespace: {{ include "agent-sandbox.namespace" . }}
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
data:
  {{- with .Values.controllerConfig }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
