apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: agent-sandbox-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: agent-sandbox-operator
    control-plane: agent-sandbox-controller
  name: agent-sandbox-controller
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: agent-sandbox-controller
status:
  loadBalancer: {}
