apiVersion: v1
data:
  enableExtensions: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: agent-sandbox-operator
  name: agent-sandbox-operator-config
