apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: sandboxwarmpool-example
spec:
  replicas: 1
  sandboxTemplateRef:
    # This name must exactly match the 'metadata.name' of your SandboxTemplate.
    name: secure-datascience-template