apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  name: python-sandbox-template
spec:
  podTemplate:
    metadata:
      labels:
        app: python-sandbox
        sandbox: codexec-python-sandbox
      annotations:
        test: "yes"
    spec:
      containers:
      - name: python-sandbox
        image: sandbox-runtime:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
