// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent_sandbox.proto

package agentsandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command and arguments (e.g., ["pip", "install", "numpy"])
	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	// Environment variables to set for this process execution context
	EnvVars       map[string]string `protobuf:"bytes,2,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type StreamOutputResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Streamed stdout output chunk
	Stdout string `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Streamed stderr output chunk
	Stderr        string `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputResponse) Reset() {
	*x = StreamOutputResponse{}
	mi := &file_agent_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputResponse) ProtoMessage() {}

func (x *StreamOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputResponse.ProtoReflect.Descriptor instead.
func (*StreamOutputResponse) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *StreamOutputResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StreamOutputResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command and arguments to run synchronously
	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	// Environment variables to set for this execution context
	EnvVars       map[string]string `protobuf:"bytes,2,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecuteRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process exit code (0 indicates success)
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Consolidated stdout output
	Stdout string `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Consolidated stderr output
	Stderr        string `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_agent_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type SendSignalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The system process ID (PID) of the process to target
	ProcessId int32 `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// The Unix signal code to send (e.g., 2 for SIGINT, 9 for SIGKILL)
	Signal        int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSignalRequest) Reset() {
	*x = SendSignalRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSignalRequest) ProtoMessage() {}

func (x *SendSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSignalRequest.ProtoReflect.Descriptor instead.
func (*SendSignalRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *SendSignalRequest) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *SendSignalRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination absolute path inside the sandbox filesystem (e.g., "/workspace/app.py")
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Raw file contents in binary format
	Content       []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ReadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source absolute path to read
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw file contents in binary format
	Content       []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_agent_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path of the directory to list
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Listed files and directories
	Entries       []*FileEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_agent_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *ListFilesResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File or directory name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// True if this entry is a directory
	IsDir bool `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	// File size in bytes (0 for directories)
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Timestamp indicating when the file was last modified
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_agent_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

type StatFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path of the target file or directory
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileRequest) Reset() {
	*x = StatFileRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileRequest) ProtoMessage() {}

func (x *StatFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileRequest.ProtoReflect.Descriptor instead.
func (*StatFileRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *StatFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved absolute path
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// True if the path is a directory
	IsDir bool `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	// File size in bytes
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Modification timestamp
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileResponse) Reset() {
	*x = StatFileResponse{}
	mi := &file_agent_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileResponse) ProtoMessage() {}

func (x *StatFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileResponse.ProtoReflect.Descriptor instead.
func (*StatFileResponse) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *StatFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatFileResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatFileResponse) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

type MakeDirRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path of the directory to create
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeDirRequest) Reset() {
	*x = MakeDirRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirRequest) ProtoMessage() {}

func (x *MakeDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirRequest.ProtoReflect.Descriptor instead.
func (*MakeDirRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *MakeDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to delete
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// If true, recursively deletes subdirectories and files
	Recursive     bool `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type CreateJupyterSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Spawns a specific language kernel (defaults to "python3")
	KernelName    string `protobuf:"bytes,1,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJupyterSessionRequest) Reset() {
	*x = CreateJupyterSessionRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJupyterSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJupyterSessionRequest) ProtoMessage() {}

func (x *CreateJupyterSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJupyterSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateJupyterSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *CreateJupyterSessionRequest) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

type JupyterSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique session identifier assigned by the sandbox kernel manager
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Status of the kernel (e.g. "starting", "idle", "busy")
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JupyterSession) Reset() {
	*x = JupyterSession{}
	mi := &file_agent_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JupyterSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JupyterSession) ProtoMessage() {}

func (x *JupyterSession) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JupyterSession.ProtoReflect.Descriptor instead.
func (*JupyterSession) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *JupyterSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JupyterSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExecuteJupyterCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target session to run the code in
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Raw python code execution block
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJupyterCodeRequest) Reset() {
	*x = ExecuteJupyterCodeRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJupyterCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJupyterCodeRequest) ProtoMessage() {}

func (x *ExecuteJupyterCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJupyterCodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteJupyterCodeRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteJupyterCodeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteJupyterCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ExecuteJupyterCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status after execution completes ("ok", "error")
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Standard stdout logs captured during execution
	Stdout string `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Standard stderr logs captured during execution
	Stderr string `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Rich execution output payloads (plots, tables, images)
	Outputs       []*JupyterOutput `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJupyterCodeResponse) Reset() {
	*x = ExecuteJupyterCodeResponse{}
	mi := &file_agent_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJupyterCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJupyterCodeResponse) ProtoMessage() {}

func (x *ExecuteJupyterCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJupyterCodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteJupyterCodeResponse) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteJupyterCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteJupyterCodeResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteJupyterCodeResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteJupyterCodeResponse) GetOutputs() []*JupyterOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type JupyterOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MIME type indicating content format (e.g., "text/plain", "image/png", "application/json")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Raw output data in binary format
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JupyterOutput) Reset() {
	*x = JupyterOutput{}
	mi := &file_agent_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JupyterOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JupyterOutput) ProtoMessage() {}

func (x *JupyterOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JupyterOutput.ProtoReflect.Descriptor instead.
func (*JupyterOutput) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *JupyterOutput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JupyterOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target URL pointing to a rootfs tarball, image, or base workspace to extract
	RootfsUrl     string `protobuf:"bytes,1,opt,name=rootfs_url,json=rootfsUrl,proto3" json:"rootfs_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *SetupRequest) GetRootfsUrl() string {
	if x != nil {
		return x.RootfsUrl
	}
	return ""
}

type CleanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanRequest) Reset() {
	*x = CleanRequest{}
	mi := &file_agent_sandbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanRequest) ProtoMessage() {}

func (x *CleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_sandbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanRequest.ProtoReflect.Descriptor instead.
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return file_agent_sandbox_proto_rawDescGZIP(), []int{21}
}

var File_agent_sandbox_proto protoreflect.FileDescriptor

const file_agent_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x13agent_sandbox.proto\x12\x0fagentsandbox.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xab\x01\n" +
	"\fStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12E\n" +
	"\benv_vars\x18\x02 \x03(\v2*.agentsandbox.v1.StartRequest.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x14StreamOutputResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\"\xaf\x01\n" +
	"\x0eExecuteRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12G\n" +
	"\benv_vars\x18\x02 \x03(\v2,.agentsandbox.v1.ExecuteRequest.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x0fExecuteResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"J\n" +
	"\x11SendSignalRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x05R\tprocessId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\"@\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"&\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"I\n" +
	"\x11ListFilesResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.agentsandbox.v1.FileEntryR\aentries\"\x81\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\"%\n" +
	"\x0fStatFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x88\x01\n" +
	"\x10StatFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\"$\n" +
	"\x0eMakeDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"A\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\">\n" +
	"\x1bCreateJupyterSessionRequest\x12\x1f\n" +
	"\vkernel_name\x18\x01 \x01(\tR\n" +
	"kernelName\"G\n" +
	"\x0eJupyterSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"N\n" +
	"\x19ExecuteJupyterCodeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x9e\x01\n" +
	"\x1aExecuteJupyterCodeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x128\n" +
	"\aoutputs\x18\x04 \x03(\v2\x1e.agentsandbox.v1.JupyterOutputR\aoutputs\"7\n" +
	"\rJupyterOutput\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"-\n" +
	"\fSetupRequest\x12\x1d\n" +
	"\n" +
	"rootfs_url\x18\x01 \x01(\tR\trootfsUrl\"\x0e\n" +
	"\fCleanRequest2\xf9\x01\n" +
	"\x0eProcessService\x12O\n" +
	"\x05Start\x12\x1d.agentsandbox.v1.StartRequest\x1a%.agentsandbox.v1.StreamOutputResponse0\x01\x12L\n" +
	"\aExecute\x12\x1f.agentsandbox.v1.ExecuteRequest\x1a .agentsandbox.v1.ExecuteResponse\x12H\n" +
	"\n" +
	"SendSignal\x12\".agentsandbox.v1.SendSignalRequest\x1a\x16.google.protobuf.Empty2\xd7\x03\n" +
	"\x11FilesystemService\x12F\n" +
	"\tWriteFile\x12!.agentsandbox.v1.WriteFileRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\bReadFile\x12 .agentsandbox.v1.ReadFileRequest\x1a!.agentsandbox.v1.ReadFileResponse\x12R\n" +
	"\tListFiles\x12!.agentsandbox.v1.ListFilesRequest\x1a\".agentsandbox.v1.ListFilesResponse\x12O\n" +
	"\bStatFile\x12 .agentsandbox.v1.StatFileRequest\x1a!.agentsandbox.v1.StatFileResponse\x12B\n" +
	"\aMakeDir\x12\x1f.agentsandbox.v1.MakeDirRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x06Remove\x12\x1e.agentsandbox.v1.RemoveRequest\x1a\x16.google.protobuf.Empty2\xd8\x01\n" +
	"\x0eJupyterService\x12^\n" +
	"\rCreateSession\x12,.agentsandbox.v1.CreateJupyterSessionRequest\x1a\x1f.agentsandbox.v1.JupyterSession\x12f\n" +
	"\vExecuteCode\x12*.agentsandbox.v1.ExecuteJupyterCodeRequest\x1a+.agentsandbox.v1.ExecuteJupyterCodeResponse2\x8e\x01\n" +
	"\fAdminService\x12>\n" +
	"\x05Setup\x12\x1d.agentsandbox.v1.SetupRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\x05Clean\x12\x1d.agentsandbox.v1.CleanRequest\x1a\x16.google.protobuf.EmptyB`\n" +
	"\x16io.agentsandbox.api.v1P\x01ZDgithub.com/kubernetes-sigs/agent-sandbox/api/proto/v1;agentsandboxv1b\x06proto3"

var (
	file_agent_sandbox_proto_rawDescOnce sync.Once
	file_agent_sandbox_proto_rawDescData []byte
)

func file_agent_sandbox_proto_rawDescGZIP() []byte {
	file_agent_sandbox_proto_rawDescOnce.Do(func() {
		file_agent_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_sandbox_proto_rawDesc), len(file_agent_sandbox_proto_rawDesc)))
	})
	return file_agent_sandbox_proto_rawDescData
}

var file_agent_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_agent_sandbox_proto_goTypes = []any{
	(*StartRequest)(nil),                // 0: agentsandbox.v1.StartRequest
	(*StreamOutputResponse)(nil),        // 1: agentsandbox.v1.StreamOutputResponse
	(*ExecuteRequest)(nil),              // 2: agentsandbox.v1.ExecuteRequest
	(*ExecuteResponse)(nil),             // 3: agentsandbox.v1.ExecuteResponse
	(*SendSignalRequest)(nil),           // 4: agentsandbox.v1.SendSignalRequest
	(*WriteFileRequest)(nil),            // 5: agentsandbox.v1.WriteFileRequest
	(*ReadFileRequest)(nil),             // 6: agentsandbox.v1.ReadFileRequest
	(*ReadFileResponse)(nil),            // 7: agentsandbox.v1.ReadFileResponse
	(*ListFilesRequest)(nil),            // 8: agentsandbox.v1.ListFilesRequest
	(*ListFilesResponse)(nil),           // 9: agentsandbox.v1.ListFilesResponse
	(*FileEntry)(nil),                   // 10: agentsandbox.v1.FileEntry
	(*StatFileRequest)(nil),             // 11: agentsandbox.v1.StatFileRequest
	(*StatFileResponse)(nil),            // 12: agentsandbox.v1.StatFileResponse
	(*MakeDirRequest)(nil),              // 13: agentsandbox.v1.MakeDirRequest
	(*RemoveRequest)(nil),               // 14: agentsandbox.v1.RemoveRequest
	(*CreateJupyterSessionRequest)(nil), // 15: agentsandbox.v1.CreateJupyterSessionRequest
	(*JupyterSession)(nil),              // 16: agentsandbox.v1.JupyterSession
	(*ExecuteJupyterCodeRequest)(nil),   // 17: agentsandbox.v1.ExecuteJupyterCodeRequest
	(*ExecuteJupyterCodeResponse)(nil),  // 18: agentsandbox.v1.ExecuteJupyterCodeResponse
	(*JupyterOutput)(nil),               // 19: agentsandbox.v1.JupyterOutput
	(*SetupRequest)(nil),                // 20: agentsandbox.v1.SetupRequest
	(*CleanRequest)(nil),                // 21: agentsandbox.v1.CleanRequest
	nil,                                 // 22: agentsandbox.v1.StartRequest.EnvVarsEntry
	nil,                                 // 23: agentsandbox.v1.ExecuteRequest.EnvVarsEntry
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 25: google.protobuf.Empty
}
var file_agent_sandbox_proto_depIdxs = []int32{
	22, // 0: agentsandbox.v1.StartRequest.env_vars:type_name -> agentsandbox.v1.StartRequest.EnvVarsEntry
	23, // 1: agentsandbox.v1.ExecuteRequest.env_vars:type_name -> agentsandbox.v1.ExecuteRequest.EnvVarsEntry
	10, // 2: agentsandbox.v1.ListFilesResponse.entries:type_name -> agentsandbox.v1.FileEntry
	24, // 3: agentsandbox.v1.FileEntry.mod_time:type_name -> google.protobuf.Timestamp
	24, // 4: agentsandbox.v1.StatFileResponse.mod_time:type_name -> google.protobuf.Timestamp
	19, // 5: agentsandbox.v1.ExecuteJupyterCodeResponse.outputs:type_name -> agentsandbox.v1.JupyterOutput
	0,  // 6: agentsandbox.v1.ProcessService.Start:input_type -> agentsandbox.v1.StartRequest
	2,  // 7: agentsandbox.v1.ProcessService.Execute:input_type -> agentsandbox.v1.ExecuteRequest
	4,  // 8: agentsandbox.v1.ProcessService.SendSignal:input_type -> agentsandbox.v1.SendSignalRequest
	5,  // 9: agentsandbox.v1.FilesystemService.WriteFile:input_type -> agentsandbox.v1.WriteFileRequest
	6,  // 10: agentsandbox.v1.FilesystemService.ReadFile:input_type -> agentsandbox.v1.ReadFileRequest
	8,  // 11: agentsandbox.v1.FilesystemService.ListFiles:input_type -> agentsandbox.v1.ListFilesRequest
	11, // 12: agentsandbox.v1.FilesystemService.StatFile:input_type -> agentsandbox.v1.StatFileRequest
	13, // 13: agentsandbox.v1.FilesystemService.MakeDir:input_type -> agentsandbox.v1.MakeDirRequest
	14, // 14: agentsandbox.v1.FilesystemService.Remove:input_type -> agentsandbox.v1.RemoveRequest
	15, // 15: agentsandbox.v1.JupyterService.CreateSession:input_type -> agentsandbox.v1.CreateJupyterSessionRequest
	17, // 16: agentsandbox.v1.JupyterService.ExecuteCode:input_type -> agentsandbox.v1.ExecuteJupyterCodeRequest
	20, // 17: agentsandbox.v1.AdminService.Setup:input_type -> agentsandbox.v1.SetupRequest
	21, // 18: agentsandbox.v1.AdminService.Clean:input_type -> agentsandbox.v1.CleanRequest
	1,  // 19: agentsandbox.v1.ProcessService.Start:output_type -> agentsandbox.v1.StreamOutputResponse
	3,  // 20: agentsandbox.v1.ProcessService.Execute:output_type -> agentsandbox.v1.ExecuteResponse
	25, // 21: agentsandbox.v1.ProcessService.SendSignal:output_type -> google.protobuf.Empty
	25, // 22: agentsandbox.v1.FilesystemService.WriteFile:output_type -> google.protobuf.Empty
	7,  // 23: agentsandbox.v1.FilesystemService.ReadFile:output_type -> agentsandbox.v1.ReadFileResponse
	9,  // 24: agentsandbox.v1.FilesystemService.ListFiles:output_type -> agentsandbox.v1.ListFilesResponse
	12, // 25: agentsandbox.v1.FilesystemService.StatFile:output_type -> agentsandbox.v1.StatFileResponse
	25, // 26: agentsandbox.v1.FilesystemService.MakeDir:output_type -> google.protobuf.Empty
	25, // 27: agentsandbox.v1.FilesystemService.Remove:output_type -> google.protobuf.Empty
	16, // 28: agentsandbox.v1.JupyterService.CreateSession:output_type -> agentsandbox.v1.JupyterSession
	18, // 29: agentsandbox.v1.JupyterService.ExecuteCode:output_type -> agentsandbox.v1.ExecuteJupyterCodeResponse
	25, // 30: agentsandbox.v1.AdminService.Setup:output_type -> google.protobuf.Empty
	25, // 31: agentsandbox.v1.AdminService.Clean:output_type -> google.protobuf.Empty
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agent_sandbox_proto_init() }
func file_agent_sandbox_proto_init() {
	if File_agent_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_sandbox_proto_rawDesc), len(file_agent_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_agent_sandbox_proto_goTypes,
		DependencyIndexes: file_agent_sandbox_proto_depIdxs,
		MessageInfos:      file_agent_sandbox_proto_msgTypes,
	}.Build()
	File_agent_sandbox_proto = out.File
	file_agent_sandbox_proto_goTypes = nil
	file_agent_sandbox_proto_depIdxs = nil
}
