kind: ServiceAccount
apiVersion: v1
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
  labels:
    app: agent-sandbox-controller
    app.kubernetes.io/name: agent-sandbox-operator
    app.kubernetes.io/managed-by: kustomize
