// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: filesystem/filesystem.proto

package filesystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_filesystem_filesystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMetadata) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WriteFileRequest_Metadata
	//	*WriteFileRequest_Chunk
	Payload       isWriteFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_filesystem_filesystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{1}
}

func (x *WriteFileRequest) GetPayload() isWriteFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*WriteFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *WriteFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WriteFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isWriteFileRequest_Payload interface {
	isWriteFileRequest_Payload()
}

type WriteFileRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type WriteFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*WriteFileRequest_Metadata) isWriteFileRequest_Payload() {}

func (*WriteFileRequest_Chunk) isWriteFileRequest_Payload() {}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_filesystem_filesystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{2}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_filesystem_filesystem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_filesystem_filesystem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_filesystem_filesystem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_filesystem_filesystem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{6}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

type StatFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileRequest) Reset() {
	*x = StatFileRequest{}
	mi := &file_filesystem_filesystem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileRequest) ProtoMessage() {}

func (x *StatFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileRequest.ProtoReflect.Descriptor instead.
func (*StatFileRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{7}
}

func (x *StatFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileResponse) Reset() {
	*x = StatFileResponse{}
	mi := &file_filesystem_filesystem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileResponse) ProtoMessage() {}

func (x *StatFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileResponse.ProtoReflect.Descriptor instead.
func (*StatFileResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{8}
}

func (x *StatFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatFileResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatFileResponse) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

type MakeDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeDirRequest) Reset() {
	*x = MakeDirRequest{}
	mi := &file_filesystem_filesystem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirRequest) ProtoMessage() {}

func (x *MakeDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirRequest.ProtoReflect.Descriptor instead.
func (*MakeDirRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{9}
}

func (x *MakeDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_filesystem_filesystem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_filesystem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_filesystem_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

var File_filesystem_filesystem_proto protoreflect.FileDescriptor

const file_filesystem_filesystem_proto_rawDesc = "" +
	"\n" +
	"\x1bfilesystem/filesystem.proto\x12\n" +
	"filesystem\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"m\n" +
	"\x10WriteFileRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.filesystem.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"(\n" +
	"\x10ReadFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"&\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"D\n" +
	"\x11ListFilesResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.filesystem.FileEntryR\aentries\"\x81\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\"%\n" +
	"\x0fStatFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x88\x01\n" +
	"\x10StatFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\"$\n" +
	"\x0eMakeDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"A\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive2\xa7\x03\n" +
	"\n" +
	"Filesystem\x12C\n" +
	"\tWriteFile\x12\x1c.filesystem.WriteFileRequest\x1a\x16.google.protobuf.Empty(\x01\x12G\n" +
	"\bReadFile\x12\x1b.filesystem.ReadFileRequest\x1a\x1c.filesystem.ReadFileResponse0\x01\x12H\n" +
	"\tListFiles\x12\x1c.filesystem.ListFilesRequest\x1a\x1d.filesystem.ListFilesResponse\x12E\n" +
	"\bStatFile\x12\x1b.filesystem.StatFileRequest\x1a\x1c.filesystem.StatFileResponse\x12=\n" +
	"\aMakeDir\x12\x1a.filesystem.MakeDirRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x06Remove\x12\x19.filesystem.RemoveRequest\x1a\x16.google.protobuf.EmptyB}\n" +
	"1io.agentsandbox.packages.sandboxd.spec.filesystemP\x01ZFsigs.k8s.io/agent-sandbox/packages/sandboxd/spec/filesystem;filesystemb\x06proto3"

var (
	file_filesystem_filesystem_proto_rawDescOnce sync.Once
	file_filesystem_filesystem_proto_rawDescData []byte
)

func file_filesystem_filesystem_proto_rawDescGZIP() []byte {
	file_filesystem_filesystem_proto_rawDescOnce.Do(func() {
		file_filesystem_filesystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filesystem_filesystem_proto_rawDesc), len(file_filesystem_filesystem_proto_rawDesc)))
	})
	return file_filesystem_filesystem_proto_rawDescData
}

var file_filesystem_filesystem_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_filesystem_filesystem_proto_goTypes = []any{
	(*FileMetadata)(nil),          // 0: filesystem.FileMetadata
	(*WriteFileRequest)(nil),      // 1: filesystem.WriteFileRequest
	(*ReadFileRequest)(nil),       // 2: filesystem.ReadFileRequest
	(*ReadFileResponse)(nil),      // 3: filesystem.ReadFileResponse
	(*ListFilesRequest)(nil),      // 4: filesystem.ListFilesRequest
	(*ListFilesResponse)(nil),     // 5: filesystem.ListFilesResponse
	(*FileEntry)(nil),             // 6: filesystem.FileEntry
	(*StatFileRequest)(nil),       // 7: filesystem.StatFileRequest
	(*StatFileResponse)(nil),      // 8: filesystem.StatFileResponse
	(*MakeDirRequest)(nil),        // 9: filesystem.MakeDirRequest
	(*RemoveRequest)(nil),         // 10: filesystem.RemoveRequest
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_filesystem_filesystem_proto_depIdxs = []int32{
	0,  // 0: filesystem.WriteFileRequest.metadata:type_name -> filesystem.FileMetadata
	6,  // 1: filesystem.ListFilesResponse.entries:type_name -> filesystem.FileEntry
	11, // 2: filesystem.FileEntry.mod_time:type_name -> google.protobuf.Timestamp
	11, // 3: filesystem.StatFileResponse.mod_time:type_name -> google.protobuf.Timestamp
	1,  // 4: filesystem.Filesystem.WriteFile:input_type -> filesystem.WriteFileRequest
	2,  // 5: filesystem.Filesystem.ReadFile:input_type -> filesystem.ReadFileRequest
	4,  // 6: filesystem.Filesystem.ListFiles:input_type -> filesystem.ListFilesRequest
	7,  // 7: filesystem.Filesystem.StatFile:input_type -> filesystem.StatFileRequest
	9,  // 8: filesystem.Filesystem.MakeDir:input_type -> filesystem.MakeDirRequest
	10, // 9: filesystem.Filesystem.Remove:input_type -> filesystem.RemoveRequest
	12, // 10: filesystem.Filesystem.WriteFile:output_type -> google.protobuf.Empty
	3,  // 11: filesystem.Filesystem.ReadFile:output_type -> filesystem.ReadFileResponse
	5,  // 12: filesystem.Filesystem.ListFiles:output_type -> filesystem.ListFilesResponse
	8,  // 13: filesystem.Filesystem.StatFile:output_type -> filesystem.StatFileResponse
	12, // 14: filesystem.Filesystem.MakeDir:output_type -> google.protobuf.Empty
	12, // 15: filesystem.Filesystem.Remove:output_type -> google.protobuf.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_filesystem_filesystem_proto_init() }
func file_filesystem_filesystem_proto_init() {
	if File_filesystem_filesystem_proto != nil {
		return
	}
	file_filesystem_filesystem_proto_msgTypes[1].OneofWrappers = []any{
		(*WriteFileRequest_Metadata)(nil),
		(*WriteFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filesystem_filesystem_proto_rawDesc), len(file_filesystem_filesystem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filesystem_filesystem_proto_goTypes,
		DependencyIndexes: file_filesystem_filesystem_proto_depIdxs,
		MessageInfos:      file_filesystem_filesystem_proto_msgTypes,
	}.Build()
	File_filesystem_filesystem_proto = out.File
	file_filesystem_filesystem_proto_goTypes = nil
	file_filesystem_filesystem_proto_depIdxs = nil
}
