// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	scheme "sigs.k8s.io/agent-sandbox/clients/k8s/extensions/clientset/versioned/scheme"
	apiv1alpha1 "sigs.k8s.io/agent-sandbox/extensions/api/v1alpha1"
)

// ManagedSandboxesGetter has a method to return a ManagedSandboxInterface.
// A group's client should implement this interface.
type ManagedSandboxesGetter interface {
	ManagedSandboxes(namespace string) ManagedSandboxInterface
}

// ManagedSandboxInterface has methods to work with ManagedSandbox resources.
type ManagedSandboxInterface interface {
	Create(ctx context.Context, managedSandbox *apiv1alpha1.ManagedSandbox, opts v1.CreateOptions) (*apiv1alpha1.ManagedSandbox, error)
	Update(ctx context.Context, managedSandbox *apiv1alpha1.ManagedSandbox, opts v1.UpdateOptions) (*apiv1alpha1.ManagedSandbox, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, managedSandbox *apiv1alpha1.ManagedSandbox, opts v1.UpdateOptions) (*apiv1alpha1.ManagedSandbox, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.ManagedSandbox, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ManagedSandboxList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.ManagedSandbox, err error)
	ManagedSandboxExpansion
}

// managedSandboxes implements ManagedSandboxInterface
type managedSandboxes struct {
	*gentype.ClientWithList[*apiv1alpha1.ManagedSandbox, *apiv1alpha1.ManagedSandboxList]
}

// newManagedSandboxes returns a ManagedSandboxes
func newManagedSandboxes(c *ExtensionsV1alpha1Client, namespace string) *managedSandboxes {
	return &managedSandboxes{
		gentype.NewClientWithList[*apiv1alpha1.ManagedSandbox, *apiv1alpha1.ManagedSandboxList](
			"managedsandboxes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.ManagedSandbox { return &apiv1alpha1.ManagedSandbox{} },
			func() *apiv1alpha1.ManagedSandboxList { return &apiv1alpha1.ManagedSandboxList{} },
		),
	}
}
