// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: admin/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootfsUrl     string                 `protobuf:"bytes,1,opt,name=rootfs_url,json=rootfsUrl,proto3" json:"rootfs_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *SetupRequest) GetRootfsUrl() string {
	if x != nil {
		return x.RootfsUrl
	}
	return ""
}

type CleanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanRequest) Reset() {
	*x = CleanRequest{}
	mi := &file_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanRequest) ProtoMessage() {}

func (x *CleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanRequest.ProtoReflect.Descriptor instead.
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{1}
}

var File_admin_admin_proto protoreflect.FileDescriptor

const file_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x11admin/admin.proto\x12\x11sandboxd.admin.v1\x1a\x1bgoogle/protobuf/empty.proto\"-\n" +
	"\fSetupRequest\x12\x1d\n" +
	"\n" +
	"rootfs_url\x18\x01 \x01(\tR\trootfsUrl\"\x0e\n" +
	"\fCleanRequest2\x8b\x01\n" +
	"\x05Admin\x12@\n" +
	"\x05Setup\x12\x1f.sandboxd.admin.v1.SetupRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x05Clean\x12\x1f.sandboxd.admin.v1.CleanRequest\x1a\x16.google.protobuf.EmptyBj\n" +
	"(io.sandboxd.packages.sandboxd.spec.adminP\x01Z<sigs.k8s.io/agent-sandbox/packages/sandboxd/spec/admin;adminb\x06proto3"

var (
	file_admin_admin_proto_rawDescOnce sync.Once
	file_admin_admin_proto_rawDescData []byte
)

func file_admin_admin_proto_rawDescGZIP() []byte {
	file_admin_admin_proto_rawDescOnce.Do(func() {
		file_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)))
	})
	return file_admin_admin_proto_rawDescData
}

var file_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_admin_admin_proto_goTypes = []any{
	(*SetupRequest)(nil),  // 0: sandboxd.admin.v1.SetupRequest
	(*CleanRequest)(nil),  // 1: sandboxd.admin.v1.CleanRequest
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_admin_admin_proto_depIdxs = []int32{
	0, // 0: sandboxd.admin.v1.Admin.Setup:input_type -> sandboxd.admin.v1.SetupRequest
	1, // 1: sandboxd.admin.v1.Admin.Clean:input_type -> sandboxd.admin.v1.CleanRequest
	2, // 2: sandboxd.admin.v1.Admin.Setup:output_type -> google.protobuf.Empty
	2, // 3: sandboxd.admin.v1.Admin.Clean:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_admin_proto_init() }
func file_admin_admin_proto_init() {
	if File_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_proto_goTypes,
		DependencyIndexes: file_admin_admin_proto_depIdxs,
		MessageInfos:      file_admin_admin_proto_msgTypes,
	}.Build()
	File_admin_admin_proto = out.File
	file_admin_admin_proto_goTypes = nil
	file_admin_admin_proto_depIdxs = nil
}
