// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "sigs.k8s.io/agent-sandbox/api/v1alpha1"
	apiv1alpha1 "sigs.k8s.io/agent-sandbox/clients/k8s/clientset/versioned/typed/api/v1alpha1"
)

// fakeSandboxes implements SandboxInterface
type fakeSandboxes struct {
	*gentype.FakeClientWithList[*v1alpha1.Sandbox, *v1alpha1.SandboxList]
	Fake *FakeAgentsV1alpha1
}

func newFakeSandboxes(fake *FakeAgentsV1alpha1, namespace string) apiv1alpha1.SandboxInterface {
	return &fakeSandboxes{
		gentype.NewFakeClientWithList[*v1alpha1.Sandbox, *v1alpha1.SandboxList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("sandboxes"),
			v1alpha1.SchemeGroupVersion.WithKind("Sandbox"),
			func() *v1alpha1.Sandbox { return &v1alpha1.Sandbox{} },
			func() *v1alpha1.SandboxList { return &v1alpha1.SandboxList{} },
			func(dst, src *v1alpha1.SandboxList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SandboxList) []*v1alpha1.Sandbox { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.SandboxList, items []*v1alpha1.Sandbox) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
