// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/agent-sandbox/api/v1beta1"
	apiv1beta1 "sigs.k8s.io/agent-sandbox/clients/k8s/clientset/versioned/typed/api/v1beta1"
)

// fakeSandboxes implements SandboxInterface
type fakeSandboxes struct {
	*gentype.FakeClientWithList[*v1beta1.Sandbox, *v1beta1.SandboxList]
	Fake *FakeAgentsV1beta1
}

func newFakeSandboxes(fake *FakeAgentsV1beta1, namespace string) apiv1beta1.SandboxInterface {
	return &fakeSandboxes{
		gentype.NewFakeClientWithList[*v1beta1.Sandbox, *v1beta1.SandboxList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("sandboxes"),
			v1beta1.SchemeGroupVersion.WithKind("Sandbox"),
			func() *v1beta1.Sandbox { return &v1beta1.Sandbox{} },
			func() *v1beta1.SandboxList { return &v1beta1.SandboxList{} },
			func(dst, src *v1beta1.SandboxList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.SandboxList) []*v1beta1.Sandbox { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.SandboxList, items []*v1beta1.Sandbox) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
