// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1beta1 "sigs.k8s.io/agent-sandbox/clients/k8s/clientset/versioned/typed/api/v1beta1"
)

type FakeAgentsV1beta1 struct {
	*testing.Fake
}

func (c *FakeAgentsV1beta1) Sandboxes(namespace string) v1beta1.SandboxInterface {
	return newFakeSandboxes(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAgentsV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
