// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: jupyter/v1/jupyter.proto

package jupyter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KernelStatus int32

const (
	KernelStatus_KERNEL_STATUS_UNSPECIFIED KernelStatus = 0
	KernelStatus_KERNEL_STATUS_STARTING    KernelStatus = 1
	KernelStatus_KERNEL_STATUS_IDLE        KernelStatus = 2
	KernelStatus_KERNEL_STATUS_BUSY        KernelStatus = 3
	KernelStatus_KERNEL_STATUS_ERROR       KernelStatus = 4
)

// Enum value maps for KernelStatus.
var (
	KernelStatus_name = map[int32]string{
		0: "KERNEL_STATUS_UNSPECIFIED",
		1: "KERNEL_STATUS_STARTING",
		2: "KERNEL_STATUS_IDLE",
		3: "KERNEL_STATUS_BUSY",
		4: "KERNEL_STATUS_ERROR",
	}
	KernelStatus_value = map[string]int32{
		"KERNEL_STATUS_UNSPECIFIED": 0,
		"KERNEL_STATUS_STARTING":    1,
		"KERNEL_STATUS_IDLE":        2,
		"KERNEL_STATUS_BUSY":        3,
		"KERNEL_STATUS_ERROR":       4,
	}
)

func (x KernelStatus) Enum() *KernelStatus {
	p := new(KernelStatus)
	*p = x
	return p
}

func (x KernelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KernelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jupyter_v1_jupyter_proto_enumTypes[0].Descriptor()
}

func (KernelStatus) Type() protoreflect.EnumType {
	return &file_jupyter_v1_jupyter_proto_enumTypes[0]
}

func (x KernelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KernelStatus.Descriptor instead.
func (KernelStatus) EnumDescriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{0}
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KernelName string `protobuf:"bytes,1,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupyter_v1_jupyter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string       `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status    KernelStatus `protobuf:"varint,2,opt,name=status,proto3,enum=jupyter.v1.KernelStatus" json:"status,omitempty"`
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupyter_v1_jupyter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetStatus() KernelStatus {
	if x != nil {
		return x.Status
	}
	return KernelStatus_KERNEL_STATUS_UNSPECIFIED
}

type ExecuteCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ExecuteCodeRequest) Reset() {
	*x = ExecuteCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupyter_v1_jupyter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeRequest) ProtoMessage() {}

func (x *ExecuteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCodeRequest) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteCodeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StreamEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdout string `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr string `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupyter_v1_jupyter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{3}
}

func (x *StreamEvent) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StreamEvent) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type StatusEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status KernelStatus `protobuf:"varint,1,opt,name=status,proto3,enum=jupyter.v1.KernelStatus" json:"status,omitempty"`
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupyter_v1_jupyter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{4}
}

func (x *StatusEvent) GetStatus() KernelStatus {
	if x != nil {
		return x.Status
	}
	return KernelStatus_KERNEL_STATUS_UNSPECIFIED
}

type ExecuteCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*ExecuteCodeResponse_Stream
	//	*ExecuteCodeResponse_Output
	//	*ExecuteCodeResponse_Status
	Event isExecuteCodeResponse_Event `protobuf_oneof:"event"`
}

func (x *ExecuteCodeResponse) Reset() {
	*x = ExecuteCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupyter_v1_jupyter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeResponse) ProtoMessage() {}

func (x *ExecuteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCodeResponse) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{5}
}

func (m *ExecuteCodeResponse) GetEvent() isExecuteCodeResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ExecuteCodeResponse) GetStream() *StreamEvent {
	if x, ok := x.GetEvent().(*ExecuteCodeResponse_Stream); ok {
		return x.Stream
	}
	return nil
}

func (x *ExecuteCodeResponse) GetOutput() *JupyterOutput {
	if x, ok := x.GetEvent().(*ExecuteCodeResponse_Output); ok {
		return x.Output
	}
	return nil
}

func (x *ExecuteCodeResponse) GetStatus() *StatusEvent {
	if x, ok := x.GetEvent().(*ExecuteCodeResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isExecuteCodeResponse_Event interface {
	isExecuteCodeResponse_Event()
}

type ExecuteCodeResponse_Stream struct {
	Stream *StreamEvent `protobuf:"bytes,1,opt,name=stream,proto3,oneof"`
}

type ExecuteCodeResponse_Output struct {
	Output *JupyterOutput `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type ExecuteCodeResponse_Status struct {
	Status *StatusEvent `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

func (*ExecuteCodeResponse_Stream) isExecuteCodeResponse_Event() {}

func (*ExecuteCodeResponse_Output) isExecuteCodeResponse_Event() {}

func (*ExecuteCodeResponse_Status) isExecuteCodeResponse_Event() {}

type JupyterOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *JupyterOutput) Reset() {
	*x = JupyterOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupyter_v1_jupyter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JupyterOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JupyterOutput) ProtoMessage() {}

func (x *JupyterOutput) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JupyterOutput.ProtoReflect.Descriptor instead.
func (*JupyterOutput) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{6}
}

func (x *JupyterOutput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JupyterOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_jupyter_v1_jupyter_proto protoreflect.FileDescriptor

var file_jupyter_v1_jupyter_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x75, 0x70,
	0x79, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6a, 0x75, 0x70, 0x79,
	0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x37, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x68, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x47, 0x0a, 0x12, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x3d, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64,
	0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72,
	0x72, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65,
	0x72, 0x6e, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x13, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6a, 0x75, 0x70,
	0x79, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x33, 0x0a,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x75, 0x70, 0x79, 0x74,
	0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x37,
	0x0a, 0x0d, 0x4a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x92, 0x01, 0x0a, 0x0c, 0x4b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x19, 0x4b, 0x45, 0x52, 0x4e,
	0x45, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x4b, 0x45, 0x52, 0x4e, 0x45,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4b, 0x45, 0x52, 0x4e, 0x45, 0x4c, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x4b,
	0x45, 0x52, 0x4e, 0x45, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x42, 0x55, 0x53,
	0x59, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x4b, 0x45, 0x52, 0x4e, 0x45, 0x4c, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x32, 0xb8, 0x01, 0x0a,
	0x0e, 0x4a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x54, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x2e, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x70, 0x0a, 0x2a, 0x69, 0x6f, 0x2e, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x64, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x64, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x6a, 0x75,
	0x70, 0x79, 0x74, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x40, 0x73, 0x69, 0x67, 0x73, 0x2e, 0x6b, 0x38,
	0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x64, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65,
	0x72, 0x3b, 0x6a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_jupyter_v1_jupyter_proto_rawDescOnce sync.Once
	file_jupyter_v1_jupyter_proto_rawDescData = file_jupyter_v1_jupyter_proto_rawDesc
)

func file_jupyter_v1_jupyter_proto_rawDescGZIP() []byte {
	file_jupyter_v1_jupyter_proto_rawDescOnce.Do(func() {
		file_jupyter_v1_jupyter_proto_rawDescData = protoimpl.X.CompressGZIP(file_jupyter_v1_jupyter_proto_rawDescData)
	})
	return file_jupyter_v1_jupyter_proto_rawDescData
}

var file_jupyter_v1_jupyter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jupyter_v1_jupyter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_jupyter_v1_jupyter_proto_goTypes = []interface{}{
	(KernelStatus)(0),             // 0: jupyter.v1.KernelStatus
	(*CreateSessionRequest)(nil),  // 1: jupyter.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 2: jupyter.v1.CreateSessionResponse
	(*ExecuteCodeRequest)(nil),    // 3: jupyter.v1.ExecuteCodeRequest
	(*StreamEvent)(nil),           // 4: jupyter.v1.StreamEvent
	(*StatusEvent)(nil),           // 5: jupyter.v1.StatusEvent
	(*ExecuteCodeResponse)(nil),   // 6: jupyter.v1.ExecuteCodeResponse
	(*JupyterOutput)(nil),         // 7: jupyter.v1.JupyterOutput
}
var file_jupyter_v1_jupyter_proto_depIdxs = []int32{
	0, // 0: jupyter.v1.CreateSessionResponse.status:type_name -> jupyter.v1.KernelStatus
	0, // 1: jupyter.v1.StatusEvent.status:type_name -> jupyter.v1.KernelStatus
	4, // 2: jupyter.v1.ExecuteCodeResponse.stream:type_name -> jupyter.v1.StreamEvent
	7, // 3: jupyter.v1.ExecuteCodeResponse.output:type_name -> jupyter.v1.JupyterOutput
	5, // 4: jupyter.v1.ExecuteCodeResponse.status:type_name -> jupyter.v1.StatusEvent
	1, // 5: jupyter.v1.JupyterService.CreateSession:input_type -> jupyter.v1.CreateSessionRequest
	3, // 6: jupyter.v1.JupyterService.ExecuteCode:input_type -> jupyter.v1.ExecuteCodeRequest
	2, // 7: jupyter.v1.JupyterService.CreateSession:output_type -> jupyter.v1.CreateSessionResponse
	6, // 8: jupyter.v1.JupyterService.ExecuteCode:output_type -> jupyter.v1.ExecuteCodeResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_jupyter_v1_jupyter_proto_init() }
func file_jupyter_v1_jupyter_proto_init() {
	if File_jupyter_v1_jupyter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jupyter_v1_jupyter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jupyter_v1_jupyter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jupyter_v1_jupyter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jupyter_v1_jupyter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jupyter_v1_jupyter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jupyter_v1_jupyter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jupyter_v1_jupyter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JupyterOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_jupyter_v1_jupyter_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ExecuteCodeResponse_Stream)(nil),
		(*ExecuteCodeResponse_Output)(nil),
		(*ExecuteCodeResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jupyter_v1_jupyter_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jupyter_v1_jupyter_proto_goTypes,
		DependencyIndexes: file_jupyter_v1_jupyter_proto_depIdxs,
		EnumInfos:         file_jupyter_v1_jupyter_proto_enumTypes,
		MessageInfos:      file_jupyter_v1_jupyter_proto_msgTypes,
	}.Build()
	File_jupyter_v1_jupyter_proto = out.File
	file_jupyter_v1_jupyter_proto_rawDesc = nil
	file_jupyter_v1_jupyter_proto_goTypes = nil
	file_jupyter_v1_jupyter_proto_depIdxs = nil
}
