// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: jupyter/v1/jupyter.proto

package jupyter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	JupyterService_CreateSession_FullMethodName = "/jupyter.v1.JupyterService/CreateSession"
	JupyterService_ExecuteCode_FullMethodName   = "/jupyter.v1.JupyterService/ExecuteCode"
)

// JupyterServiceClient is the client API for JupyterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JupyterServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	ExecuteCode(ctx context.Context, in *ExecuteCodeRequest, opts ...grpc.CallOption) (JupyterService_ExecuteCodeClient, error)
}

type jupyterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJupyterServiceClient(cc grpc.ClientConnInterface) JupyterServiceClient {
	return &jupyterServiceClient{cc}
}

func (c *jupyterServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, JupyterService_CreateSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jupyterServiceClient) ExecuteCode(ctx context.Context, in *ExecuteCodeRequest, opts ...grpc.CallOption) (JupyterService_ExecuteCodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &JupyterService_ServiceDesc.Streams[0], JupyterService_ExecuteCode_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &jupyterServiceExecuteCodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JupyterService_ExecuteCodeClient interface {
	Recv() (*ExecuteCodeResponse, error)
	grpc.ClientStream
}

type jupyterServiceExecuteCodeClient struct {
	grpc.ClientStream
}

func (x *jupyterServiceExecuteCodeClient) Recv() (*ExecuteCodeResponse, error) {
	m := new(ExecuteCodeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JupyterServiceServer is the server API for JupyterService service.
// All implementations must embed UnimplementedJupyterServiceServer
// for forward compatibility
type JupyterServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	ExecuteCode(*ExecuteCodeRequest, JupyterService_ExecuteCodeServer) error
	mustEmbedUnimplementedJupyterServiceServer()
}

// UnimplementedJupyterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJupyterServiceServer struct {
}

func (UnimplementedJupyterServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedJupyterServiceServer) ExecuteCode(*ExecuteCodeRequest, JupyterService_ExecuteCodeServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteCode not implemented")
}
func (UnimplementedJupyterServiceServer) mustEmbedUnimplementedJupyterServiceServer() {}

// UnsafeJupyterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JupyterServiceServer will
// result in compilation errors.
type UnsafeJupyterServiceServer interface {
	mustEmbedUnimplementedJupyterServiceServer()
}

func RegisterJupyterServiceServer(s grpc.ServiceRegistrar, srv JupyterServiceServer) {
	s.RegisterService(&JupyterService_ServiceDesc, srv)
}

func _JupyterService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JupyterServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JupyterService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JupyterServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JupyterService_ExecuteCode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteCodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JupyterServiceServer).ExecuteCode(m, &jupyterServiceExecuteCodeServer{stream})
}

type JupyterService_ExecuteCodeServer interface {
	Send(*ExecuteCodeResponse) error
	grpc.ServerStream
}

type jupyterServiceExecuteCodeServer struct {
	grpc.ServerStream
}

func (x *jupyterServiceExecuteCodeServer) Send(m *ExecuteCodeResponse) error {
	return x.ServerStream.SendMsg(m)
}

// JupyterService_ServiceDesc is the grpc.ServiceDesc for JupyterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JupyterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jupyter.v1.JupyterService",
	HandlerType: (*JupyterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _JupyterService_CreateSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteCode",
			Handler:       _JupyterService_ExecuteCode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jupyter/v1/jupyter.proto",
}
