// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: jupyter/v1/jupyter.proto

package jupyter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KernelStatus int32

const (
	KernelStatus_KERNEL_STATUS_UNSPECIFIED KernelStatus = 0
	KernelStatus_KERNEL_STATUS_STARTING    KernelStatus = 1
	KernelStatus_KERNEL_STATUS_IDLE        KernelStatus = 2
	KernelStatus_KERNEL_STATUS_BUSY        KernelStatus = 3
	KernelStatus_KERNEL_STATUS_ERROR       KernelStatus = 4
)

// Enum value maps for KernelStatus.
var (
	KernelStatus_name = map[int32]string{
		0: "KERNEL_STATUS_UNSPECIFIED",
		1: "KERNEL_STATUS_STARTING",
		2: "KERNEL_STATUS_IDLE",
		3: "KERNEL_STATUS_BUSY",
		4: "KERNEL_STATUS_ERROR",
	}
	KernelStatus_value = map[string]int32{
		"KERNEL_STATUS_UNSPECIFIED": 0,
		"KERNEL_STATUS_STARTING":    1,
		"KERNEL_STATUS_IDLE":        2,
		"KERNEL_STATUS_BUSY":        3,
		"KERNEL_STATUS_ERROR":       4,
	}
)

func (x KernelStatus) Enum() *KernelStatus {
	p := new(KernelStatus)
	*p = x
	return p
}

func (x KernelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KernelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jupyter_v1_jupyter_proto_enumTypes[0].Descriptor()
}

func (KernelStatus) Type() protoreflect.EnumType {
	return &file_jupyter_v1_jupyter_proto_enumTypes[0]
}

func (x KernelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KernelStatus.Descriptor instead.
func (KernelStatus) EnumDescriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{0}
}

type CreateJupyterSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelName    string                 `protobuf:"bytes,1,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJupyterSessionRequest) Reset() {
	*x = CreateJupyterSessionRequest{}
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJupyterSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJupyterSessionRequest) ProtoMessage() {}

func (x *CreateJupyterSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJupyterSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateJupyterSessionRequest) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJupyterSessionRequest) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

type JupyterSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        KernelStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=jupyter.v1.KernelStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JupyterSession) Reset() {
	*x = JupyterSession{}
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JupyterSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JupyterSession) ProtoMessage() {}

func (x *JupyterSession) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JupyterSession.ProtoReflect.Descriptor instead.
func (*JupyterSession) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{1}
}

func (x *JupyterSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JupyterSession) GetStatus() KernelStatus {
	if x != nil {
		return x.Status
	}
	return KernelStatus_KERNEL_STATUS_UNSPECIFIED
}

type ExecuteJupyterCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJupyterCodeRequest) Reset() {
	*x = ExecuteJupyterCodeRequest{}
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJupyterCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJupyterCodeRequest) ProtoMessage() {}

func (x *ExecuteJupyterCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJupyterCodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteJupyterCodeRequest) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteJupyterCodeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteJupyterCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{3}
}

func (x *StreamEvent) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StreamEvent) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        KernelStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=jupyter.v1.KernelStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{4}
}

func (x *StatusEvent) GetStatus() KernelStatus {
	if x != nil {
		return x.Status
	}
	return KernelStatus_KERNEL_STATUS_UNSPECIFIED
}

type ExecuteJupyterCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteJupyterCodeResponse_Stream
	//	*ExecuteJupyterCodeResponse_Output
	//	*ExecuteJupyterCodeResponse_Status
	Event         isExecuteJupyterCodeResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJupyterCodeResponse) Reset() {
	*x = ExecuteJupyterCodeResponse{}
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJupyterCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJupyterCodeResponse) ProtoMessage() {}

func (x *ExecuteJupyterCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJupyterCodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteJupyterCodeResponse) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteJupyterCodeResponse) GetEvent() isExecuteJupyterCodeResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteJupyterCodeResponse) GetStream() *StreamEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteJupyterCodeResponse_Stream); ok {
			return x.Stream
		}
	}
	return nil
}

func (x *ExecuteJupyterCodeResponse) GetOutput() *JupyterOutput {
	if x != nil {
		if x, ok := x.Event.(*ExecuteJupyterCodeResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ExecuteJupyterCodeResponse) GetStatus() *StatusEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteJupyterCodeResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isExecuteJupyterCodeResponse_Event interface {
	isExecuteJupyterCodeResponse_Event()
}

type ExecuteJupyterCodeResponse_Stream struct {
	Stream *StreamEvent `protobuf:"bytes,1,opt,name=stream,proto3,oneof"`
}

type ExecuteJupyterCodeResponse_Output struct {
	Output *JupyterOutput `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type ExecuteJupyterCodeResponse_Status struct {
	Status *StatusEvent `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

func (*ExecuteJupyterCodeResponse_Stream) isExecuteJupyterCodeResponse_Event() {}

func (*ExecuteJupyterCodeResponse_Output) isExecuteJupyterCodeResponse_Event() {}

func (*ExecuteJupyterCodeResponse_Status) isExecuteJupyterCodeResponse_Event() {}

type JupyterOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JupyterOutput) Reset() {
	*x = JupyterOutput{}
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JupyterOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JupyterOutput) ProtoMessage() {}

func (x *JupyterOutput) ProtoReflect() protoreflect.Message {
	mi := &file_jupyter_v1_jupyter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JupyterOutput.ProtoReflect.Descriptor instead.
func (*JupyterOutput) Descriptor() ([]byte, []int) {
	return file_jupyter_v1_jupyter_proto_rawDescGZIP(), []int{6}
}

func (x *JupyterOutput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JupyterOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_jupyter_v1_jupyter_proto protoreflect.FileDescriptor

const file_jupyter_v1_jupyter_proto_rawDesc = "" +
	"\n" +
	"\x18jupyter/v1/jupyter.proto\x12\n" +
	"jupyter.v1\">\n" +
	"\x1bCreateJupyterSessionRequest\x12\x1f\n" +
	"\vkernel_name\x18\x01 \x01(\tR\n" +
	"kernelName\"a\n" +
	"\x0eJupyterSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.jupyter.v1.KernelStatusR\x06status\"N\n" +
	"\x19ExecuteJupyterCodeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"=\n" +
	"\vStreamEvent\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\"?\n" +
	"\vStatusEvent\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.jupyter.v1.KernelStatusR\x06status\"\xc0\x01\n" +
	"\x1aExecuteJupyterCodeResponse\x121\n" +
	"\x06stream\x18\x01 \x01(\v2\x17.jupyter.v1.StreamEventH\x00R\x06stream\x123\n" +
	"\x06output\x18\x02 \x01(\v2\x19.jupyter.v1.JupyterOutputH\x00R\x06output\x121\n" +
	"\x06status\x18\x03 \x01(\v2\x17.jupyter.v1.StatusEventH\x00R\x06statusB\a\n" +
	"\x05event\"7\n" +
	"\rJupyterOutput\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data*\x92\x01\n" +
	"\fKernelStatus\x12\x1d\n" +
	"\x19KERNEL_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16KERNEL_STATUS_STARTING\x10\x01\x12\x16\n" +
	"\x12KERNEL_STATUS_IDLE\x10\x02\x12\x16\n" +
	"\x12KERNEL_STATUS_BUSY\x10\x03\x12\x17\n" +
	"\x13KERNEL_STATUS_ERROR\x10\x042\xbf\x01\n" +
	"\aJupyter\x12T\n" +
	"\rCreateSession\x12'.jupyter.v1.CreateJupyterSessionRequest\x1a\x1a.jupyter.v1.JupyterSession\x12^\n" +
	"\vExecuteCode\x12%.jupyter.v1.ExecuteJupyterCodeRequest\x1a&.jupyter.v1.ExecuteJupyterCodeResponse0\x01Bp\n" +
	"*io.sandboxd.packages.sandboxd.spec.jupyterP\x01Z@sigs.k8s.io/agent-sandbox/packages/sandboxd/spec/jupyter;jupyterb\x06proto3"

var (
	file_jupyter_v1_jupyter_proto_rawDescOnce sync.Once
	file_jupyter_v1_jupyter_proto_rawDescData []byte
)

func file_jupyter_v1_jupyter_proto_rawDescGZIP() []byte {
	file_jupyter_v1_jupyter_proto_rawDescOnce.Do(func() {
		file_jupyter_v1_jupyter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jupyter_v1_jupyter_proto_rawDesc), len(file_jupyter_v1_jupyter_proto_rawDesc)))
	})
	return file_jupyter_v1_jupyter_proto_rawDescData
}

var file_jupyter_v1_jupyter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jupyter_v1_jupyter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_jupyter_v1_jupyter_proto_goTypes = []any{
	(KernelStatus)(0),                   // 0: jupyter.v1.KernelStatus
	(*CreateJupyterSessionRequest)(nil), // 1: jupyter.v1.CreateJupyterSessionRequest
	(*JupyterSession)(nil),              // 2: jupyter.v1.JupyterSession
	(*ExecuteJupyterCodeRequest)(nil),   // 3: jupyter.v1.ExecuteJupyterCodeRequest
	(*StreamEvent)(nil),                 // 4: jupyter.v1.StreamEvent
	(*StatusEvent)(nil),                 // 5: jupyter.v1.StatusEvent
	(*ExecuteJupyterCodeResponse)(nil),  // 6: jupyter.v1.ExecuteJupyterCodeResponse
	(*JupyterOutput)(nil),               // 7: jupyter.v1.JupyterOutput
}
var file_jupyter_v1_jupyter_proto_depIdxs = []int32{
	0, // 0: jupyter.v1.JupyterSession.status:type_name -> jupyter.v1.KernelStatus
	0, // 1: jupyter.v1.StatusEvent.status:type_name -> jupyter.v1.KernelStatus
	4, // 2: jupyter.v1.ExecuteJupyterCodeResponse.stream:type_name -> jupyter.v1.StreamEvent
	7, // 3: jupyter.v1.ExecuteJupyterCodeResponse.output:type_name -> jupyter.v1.JupyterOutput
	5, // 4: jupyter.v1.ExecuteJupyterCodeResponse.status:type_name -> jupyter.v1.StatusEvent
	1, // 5: jupyter.v1.Jupyter.CreateSession:input_type -> jupyter.v1.CreateJupyterSessionRequest
	3, // 6: jupyter.v1.Jupyter.ExecuteCode:input_type -> jupyter.v1.ExecuteJupyterCodeRequest
	2, // 7: jupyter.v1.Jupyter.CreateSession:output_type -> jupyter.v1.JupyterSession
	6, // 8: jupyter.v1.Jupyter.ExecuteCode:output_type -> jupyter.v1.ExecuteJupyterCodeResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_jupyter_v1_jupyter_proto_init() }
func file_jupyter_v1_jupyter_proto_init() {
	if File_jupyter_v1_jupyter_proto != nil {
		return
	}
	file_jupyter_v1_jupyter_proto_msgTypes[5].OneofWrappers = []any{
		(*ExecuteJupyterCodeResponse_Stream)(nil),
		(*ExecuteJupyterCodeResponse_Output)(nil),
		(*ExecuteJupyterCodeResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jupyter_v1_jupyter_proto_rawDesc), len(file_jupyter_v1_jupyter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jupyter_v1_jupyter_proto_goTypes,
		DependencyIndexes: file_jupyter_v1_jupyter_proto_depIdxs,
		EnumInfos:         file_jupyter_v1_jupyter_proto_enumTypes,
		MessageInfos:      file_jupyter_v1_jupyter_proto_msgTypes,
	}.Build()
	File_jupyter_v1_jupyter_proto = out.File
	file_jupyter_v1_jupyter_proto_goTypes = nil
	file_jupyter_v1_jupyter_proto_depIdxs = nil
}
