// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: filesystem/v1/filesystem.proto

package filesystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FILE_TYPE_UNSPECIFIED FileType = 0
	FileType_FILE_TYPE_FILE        FileType = 1
	FileType_FILE_TYPE_DIRECTORY   FileType = 2
	FileType_FILE_TYPE_SYMLINK     FileType = 3
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_UNSPECIFIED",
		1: "FILE_TYPE_FILE",
		2: "FILE_TYPE_DIRECTORY",
		3: "FILE_TYPE_SYMLINK",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_UNSPECIFIED": 0,
		"FILE_TYPE_FILE":        1,
		"FILE_TYPE_DIRECTORY":   2,
		"FILE_TYPE_SYMLINK":     3,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_filesystem_v1_filesystem_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_filesystem_v1_filesystem_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{0}
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          *uint32                `protobuf:"varint,2,opt,name=mode,proto3,oneof" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMetadata) GetMode() uint32 {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return 0
}

type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WriteFileRequest_Metadata
	//	*WriteFileRequest_Chunk
	Payload       isWriteFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{1}
}

func (x *WriteFileRequest) GetPayload() isWriteFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*WriteFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *WriteFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WriteFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isWriteFileRequest_Payload interface {
	isWriteFileRequest_Payload()
}

type WriteFileRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type WriteFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*WriteFileRequest_Metadata) isWriteFileRequest_Payload() {}

func (*WriteFileRequest_Chunk) isWriteFileRequest_Payload() {}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{2}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FileType               `protobuf:"varint,2,opt,name=type,proto3,enum=filesystem.v1.FileType" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{6}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

type StatFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileRequest) Reset() {
	*x = StatFileRequest{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileRequest) ProtoMessage() {}

func (x *StatFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileRequest.ProtoReflect.Descriptor instead.
func (*StatFileRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{7}
}

func (x *StatFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          FileType               `protobuf:"varint,2,opt,name=type,proto3,enum=filesystem.v1.FileType" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileResponse) Reset() {
	*x = StatFileResponse{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileResponse) ProtoMessage() {}

func (x *StatFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileResponse.ProtoReflect.Descriptor instead.
func (*StatFileResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{8}
}

func (x *StatFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatFileResponse) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *StatFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatFileResponse) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

type MakeDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeDirRequest) Reset() {
	*x = MakeDirRequest{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirRequest) ProtoMessage() {}

func (x *MakeDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirRequest.ProtoReflect.Descriptor instead.
func (*MakeDirRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{9}
}

func (x *MakeDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_filesystem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_filesystem_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

var File_filesystem_v1_filesystem_proto protoreflect.FileDescriptor

const file_filesystem_v1_filesystem_proto_rawDesc = "" +
	"\n" +
	"\x1efilesystem/v1/filesystem.proto\x12\rfilesystem.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\x04mode\x18\x02 \x01(\rH\x00R\x04mode\x88\x01\x01B\a\n" +
	"\x05_mode\"p\n" +
	"\x10WriteFileRequest\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.filesystem.v1.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"(\n" +
	"\x10ReadFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"&\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"G\n" +
	"\x11ListFilesResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.filesystem.v1.FileEntryR\aentries\"\x97\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.filesystem.v1.FileTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\"%\n" +
	"\x0fStatFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x9e\x01\n" +
	"\x10StatFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.filesystem.v1.FileTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\"$\n" +
	"\x0eMakeDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"A\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive*i\n" +
	"\bFileType\x12\x19\n" +
	"\x15FILE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eFILE_TYPE_FILE\x10\x01\x12\x17\n" +
	"\x13FILE_TYPE_DIRECTORY\x10\x02\x12\x15\n" +
	"\x11FILE_TYPE_SYMLINK\x10\x032\xc2\x03\n" +
	"\n" +
	"Filesystem\x12F\n" +
	"\tWriteFile\x12\x1f.filesystem.v1.WriteFileRequest\x1a\x16.google.protobuf.Empty(\x01\x12M\n" +
	"\bReadFile\x12\x1e.filesystem.v1.ReadFileRequest\x1a\x1f.filesystem.v1.ReadFileResponse0\x01\x12N\n" +
	"\tListFiles\x12\x1f.filesystem.v1.ListFilesRequest\x1a .filesystem.v1.ListFilesResponse\x12K\n" +
	"\bStatFile\x12\x1e.filesystem.v1.StatFileRequest\x1a\x1f.filesystem.v1.StatFileResponse\x12@\n" +
	"\aMakeDir\x12\x1d.filesystem.v1.MakeDirRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\x06Remove\x12\x1c.filesystem.v1.RemoveRequest\x1a\x16.google.protobuf.EmptyBy\n" +
	"-io.sandboxd.packages.sandboxd.spec.filesystemP\x01ZFsigs.k8s.io/agent-sandbox/packages/sandboxd/spec/filesystem;filesystemb\x06proto3"

var (
	file_filesystem_v1_filesystem_proto_rawDescOnce sync.Once
	file_filesystem_v1_filesystem_proto_rawDescData []byte
)

func file_filesystem_v1_filesystem_proto_rawDescGZIP() []byte {
	file_filesystem_v1_filesystem_proto_rawDescOnce.Do(func() {
		file_filesystem_v1_filesystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filesystem_v1_filesystem_proto_rawDesc), len(file_filesystem_v1_filesystem_proto_rawDesc)))
	})
	return file_filesystem_v1_filesystem_proto_rawDescData
}

var file_filesystem_v1_filesystem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_filesystem_v1_filesystem_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_filesystem_v1_filesystem_proto_goTypes = []any{
	(FileType)(0),                 // 0: filesystem.v1.FileType
	(*FileMetadata)(nil),          // 1: filesystem.v1.FileMetadata
	(*WriteFileRequest)(nil),      // 2: filesystem.v1.WriteFileRequest
	(*ReadFileRequest)(nil),       // 3: filesystem.v1.ReadFileRequest
	(*ReadFileResponse)(nil),      // 4: filesystem.v1.ReadFileResponse
	(*ListFilesRequest)(nil),      // 5: filesystem.v1.ListFilesRequest
	(*ListFilesResponse)(nil),     // 6: filesystem.v1.ListFilesResponse
	(*FileEntry)(nil),             // 7: filesystem.v1.FileEntry
	(*StatFileRequest)(nil),       // 8: filesystem.v1.StatFileRequest
	(*StatFileResponse)(nil),      // 9: filesystem.v1.StatFileResponse
	(*MakeDirRequest)(nil),        // 10: filesystem.v1.MakeDirRequest
	(*RemoveRequest)(nil),         // 11: filesystem.v1.RemoveRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_filesystem_v1_filesystem_proto_depIdxs = []int32{
	1,  // 0: filesystem.v1.WriteFileRequest.metadata:type_name -> filesystem.v1.FileMetadata
	7,  // 1: filesystem.v1.ListFilesResponse.entries:type_name -> filesystem.v1.FileEntry
	0,  // 2: filesystem.v1.FileEntry.type:type_name -> filesystem.v1.FileType
	12, // 3: filesystem.v1.FileEntry.mod_time:type_name -> google.protobuf.Timestamp
	0,  // 4: filesystem.v1.StatFileResponse.type:type_name -> filesystem.v1.FileType
	12, // 5: filesystem.v1.StatFileResponse.mod_time:type_name -> google.protobuf.Timestamp
	2,  // 6: filesystem.v1.Filesystem.WriteFile:input_type -> filesystem.v1.WriteFileRequest
	3,  // 7: filesystem.v1.Filesystem.ReadFile:input_type -> filesystem.v1.ReadFileRequest
	5,  // 8: filesystem.v1.Filesystem.ListFiles:input_type -> filesystem.v1.ListFilesRequest
	8,  // 9: filesystem.v1.Filesystem.StatFile:input_type -> filesystem.v1.StatFileRequest
	10, // 10: filesystem.v1.Filesystem.MakeDir:input_type -> filesystem.v1.MakeDirRequest
	11, // 11: filesystem.v1.Filesystem.Remove:input_type -> filesystem.v1.RemoveRequest
	13, // 12: filesystem.v1.Filesystem.WriteFile:output_type -> google.protobuf.Empty
	4,  // 13: filesystem.v1.Filesystem.ReadFile:output_type -> filesystem.v1.ReadFileResponse
	6,  // 14: filesystem.v1.Filesystem.ListFiles:output_type -> filesystem.v1.ListFilesResponse
	9,  // 15: filesystem.v1.Filesystem.StatFile:output_type -> filesystem.v1.StatFileResponse
	13, // 16: filesystem.v1.Filesystem.MakeDir:output_type -> google.protobuf.Empty
	13, // 17: filesystem.v1.Filesystem.Remove:output_type -> google.protobuf.Empty
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_filesystem_v1_filesystem_proto_init() }
func file_filesystem_v1_filesystem_proto_init() {
	if File_filesystem_v1_filesystem_proto != nil {
		return
	}
	file_filesystem_v1_filesystem_proto_msgTypes[0].OneofWrappers = []any{}
	file_filesystem_v1_filesystem_proto_msgTypes[1].OneofWrappers = []any{
		(*WriteFileRequest_Metadata)(nil),
		(*WriteFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filesystem_v1_filesystem_proto_rawDesc), len(file_filesystem_v1_filesystem_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filesystem_v1_filesystem_proto_goTypes,
		DependencyIndexes: file_filesystem_v1_filesystem_proto_depIdxs,
		EnumInfos:         file_filesystem_v1_filesystem_proto_enumTypes,
		MessageInfos:      file_filesystem_v1_filesystem_proto_msgTypes,
	}.Build()
	File_filesystem_v1_filesystem_proto = out.File
	file_filesystem_v1_filesystem_proto_goTypes = nil
	file_filesystem_v1_filesystem_proto_depIdxs = nil
}
