// Code generated by informer-gen. DO NOT EDIT.

package clients\k8s\informers\externalversions

import (
	v1alpha1 "sigs.k8s.io/agent-sandbox/api/v1alpha1"
	fmt "fmt"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)


// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
		// Group=agents.x-k8s.io, Version=v1alpha1
				case v1alpha1.SchemeGroupVersion.WithResource("sandboxes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Agents().V1alpha1().Sandboxes().Informer()}, nil
				
			
		}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
