apiVersion: v1
kind: ServiceAccount
metadata:
  name: rllib-sandbox
  namespace: rllib-sandbox-example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rllib-submitter
  namespace: rllib-sandbox-example
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rllib-sandbox
  namespace: rllib-sandbox-example
rules:
  - apiGroups: ["extensions.agents.x-k8s.io"]
    resources: ["sandboxclaims"]
    verbs: ["create", "get", "watch", "delete"]
  - apiGroups: ["agents.x-k8s.io"]
    resources: ["sandboxes"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rllib-sandbox
  namespace: rllib-sandbox-example
subjects:
  - kind: ServiceAccount
    name: rllib-sandbox
    namespace: rllib-sandbox-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rllib-sandbox
