// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

const (
	// RuntimeAdoptionWireVersion identifies the supported same-policy adoption contract.
	RuntimeAdoptionWireVersion = "runtime.gatekeeper.sh/same-policy-adoption/v1alpha1"
	// RuntimeAdoptionFinalizer retains ownership evidence until runtime cleanup is confirmed.
	RuntimeAdoptionFinalizer = "agents.x-k8s.io/runtime-adoption-protection"
)

// RuntimeAdoptionID identifies an initialization, activation, or durable adoption attempt.
// IDs must be generated by a trusted controller; their syntax does not establish authority.
// +kubebuilder:validation:MinLength=16
// +kubebuilder:validation:MaxLength=128
// +kubebuilder:validation:Pattern=`^[A-Za-z0-9._-]+$`
type RuntimeAdoptionID string

// RuntimeAdoptionDigest identifies a domain-separated canonical SHA-256 payload.
// +kubebuilder:validation:MinLength=71
// +kubebuilder:validation:MaxLength=71
// +kubebuilder:validation:Pattern=`^sha256:[0-9a-f]{64}$`
type RuntimeAdoptionDigest string

// RuntimeAdoptionObjectReference keeps a UID-bound locator through deletion and recovery.
type RuntimeAdoptionObjectReference struct {
	// name locates the referenced object.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	Name string `json:"name"`

	// uid distinguishes the original object from a replacement with the same name.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	UID types.UID `json:"uid"`
}

// RuntimeAdoptionReservation binds one live claim to one initialized sandbox.
// Both the claim and sandbox must contain this exact reservation before a runtime
// may act. Names locate objects; UIDs, authenticated writers, and live readback
// establish their identities. Resource versions are optimistic-write fences and
// are deliberately absent from this immutable protocol context.
type RuntimeAdoptionReservation struct {
	// wireVersion identifies the canonical reservation encoding.
	// +required
	// +kubebuilder:validation:Enum="runtime.gatekeeper.sh/same-policy-adoption/v1alpha1"
	WireVersion string `json:"wireVersion"`

	// attemptID identifies this attempt across retries and controller restarts.
	// +required
	AttemptID RuntimeAdoptionID `json:"attemptID"`

	// initializationID identifies the verified first-claim-only pool initialization.
	// +required
	InitializationID RuntimeAdoptionID `json:"initializationID"`

	// sourceActivationID is the expected predecessor that currently owns the execution.
	// +required
	SourceActivationID RuntimeAdoptionID `json:"sourceActivationID"`

	// targetActivationID is the only permitted successor for this attempt.
	// +required
	TargetActivationID RuntimeAdoptionID `json:"targetActivationID"`

	// namespace is shared by the claim, sandbox, pool, and template.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	Namespace string `json:"namespace"`

	// namespaceUID prevents a recreated namespace from reusing this reservation.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	NamespaceUID types.UID `json:"namespaceUID"`

	// claimName locates the claiming SandboxClaim.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	ClaimName string `json:"claimName"`

	// claimUID is the identity of the claiming SandboxClaim.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	ClaimUID types.UID `json:"claimUID"`

	// claimGeneration records the claim spec accepted for the attempt.
	// +required
	// +kubebuilder:validation:Minimum=1
	ClaimGeneration int64 `json:"claimGeneration"`

	// claimIntentDigest also covers metadata inputs that do not increment generation.
	// +required
	ClaimIntentDigest RuntimeAdoptionDigest `json:"claimIntentDigest"`

	// sandboxUID is the identity of the exclusively reserved Sandbox.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	SandboxUID types.UID `json:"sandboxUID"`

	// poolUID is the identity of the original SandboxWarmPool.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	PoolUID types.UID `json:"poolUID"`

	// templateUID is the identity of the initialized SandboxTemplate.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	TemplateUID types.UID `json:"templateUID"`

	// expiresAt bounds new authorization; expiry never returns uncertain execution to the pool.
	// +required
	ExpiresAt metav1.Time `json:"expiresAt"`
}

// RuntimeAdoptionInitialization references authenticated strict pool initialization.
// Only the signed envelope and matching live runtime state establish eligibility;
// the summary fields are not independent authorization.
type RuntimeAdoptionInitialization struct {
	// initializationID identifies the original initialization observation.
	// +required
	InitializationID RuntimeAdoptionID `json:"initializationID"`

	// sourceActivationID identifies the strict cold activation used to initialize the pool member.
	// +required
	SourceActivationID RuntimeAdoptionID `json:"sourceActivationID"`

	// poolUID identifies the pool that created the unused sandbox.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	PoolUID types.UID `json:"poolUID"`

	// templateUID identifies the template used for initialization.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	TemplateUID types.UID `json:"templateUID"`

	// blueprintDigest binds the versioned immutable workload projection.
	// +required
	BlueprintDigest RuntimeAdoptionDigest `json:"blueprintDigest"`

	// receiptDigest identifies the original strict cold activation receipt.
	// +required
	ReceiptDigest RuntimeAdoptionDigest `json:"receiptDigest"`

	// envelope contains the canonical signed initialization envelope, encoded as base64
	// in JSON. Opaque bytes preserve the signed encoding through API-server storage.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=262144
	Envelope []byte `json:"envelope"`
}

// RuntimeAdoptionGrant records the API-side authorization for one held transfer receipt.
// The node must independently verify it and durably consume its signed grant once.
type RuntimeAdoptionGrant struct {
	// contextDigest identifies the immutable prepared adoption context.
	// +required
	ContextDigest RuntimeAdoptionDigest `json:"contextDigest"`

	// receiptDigest identifies the held target receipt authorized for release.
	// +required
	ReceiptDigest RuntimeAdoptionDigest `json:"receiptDigest"`

	// expiresAt must not exceed the reservation, preparation, or receipt deadline.
	// +required
	ExpiresAt metav1.Time `json:"expiresAt"`

	// grantDigest identifies the node-signed start grant after it has been observed.
	// +optional
	GrantDigest RuntimeAdoptionDigest `json:"grantDigest,omitempty"`
}

// RuntimeAdoptionConsumption permanently retires a sandbox's first-claim eligibility.
// It is distinct from the node's consumption of release authorization. A failed
// attempt that may have held execution also consumes eligibility.
type RuntimeAdoptionConsumption struct {
	// attemptID identifies the attempt that retired the sandbox from the pool.
	// +required
	AttemptID RuntimeAdoptionID `json:"attemptID"`

	// claimUID identifies that attempt's claim even after the claim is deleted.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	ClaimUID types.UID `json:"claimUID"`

	// consumedTime records when first-claim eligibility was retired.
	// +required
	ConsumedTime metav1.Time `json:"consumedTime"`
}

// RuntimeAdoptionStatus is owned by the trusted claim controller.
// Protected fields require authenticated writers and admission checks; their
// presence alone does not enable warm execution or authorize any runtime action.
type RuntimeAdoptionStatus struct {
	// initialization retains the first-use origin for the lifetime of the sandbox.
	// +optional
	Initialization *RuntimeAdoptionInitialization `json:"initialization,omitempty"`

	// reservation is exclusive and survives cancellation until the node proves a terminal result.
	// +optional
	Reservation *RuntimeAdoptionReservation `json:"reservation,omitempty"`

	// holdEvidenceDigest records the authenticated hold before ownership or metadata changes.
	// +optional
	HoldEvidenceDigest RuntimeAdoptionDigest `json:"holdEvidenceDigest,omitempty"`

	// targetMetadataDigest identifies the final API-server-observed target metadata.
	// +optional
	TargetMetadataDigest RuntimeAdoptionDigest `json:"targetMetadataDigest,omitempty"`

	// grant records the accepted API-side release authorization.
	// +optional
	Grant *RuntimeAdoptionGrant `json:"grant,omitempty"`

	// commitDigest identifies the immutable, confirmed runtime release result.
	// +optional
	CommitDigest RuntimeAdoptionDigest `json:"commitDigest,omitempty"`

	// terminationRequestedTime requests owner-aware cleanup without erasing the attempt.
	// Once set, no new release authorization may be issued for this reservation.
	// +optional
	TerminationRequestedTime *metav1.Time `json:"terminationRequestedTime,omitempty"`

	// consumed permanently prevents this sandbox from serving another first claim.
	// +optional
	Consumed *RuntimeAdoptionConsumption `json:"consumed,omitempty"`

	// terminalEvidenceDigest identifies the retained node observation used for finalization.
	// +optional
	TerminalEvidenceDigest RuntimeAdoptionDigest `json:"terminalEvidenceDigest,omitempty"`

	// conditions record observed adoption progress without replacing the durable identity.
	// +optional
	// +listType=map
	// +listMapKey=type
	// +kubebuilder:validation:MaxItems=16
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// RuntimeActivationVerification is owned exclusively by the GKR readiness controller.
// A claim must match the complete current verification and its validity deadline;
// a Ready condition or receipt for the same Pod under another attempt is insufficient.
type RuntimeActivationVerification struct {
	// attemptID identifies the committed adoption being verified.
	// +required
	AttemptID RuntimeAdoptionID `json:"attemptID"`

	// claimUID identifies the current claimant.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	ClaimUID types.UID `json:"claimUID"`

	// podUID identifies the retained Pod verified by the runtime controller.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	PodUID types.UID `json:"podUID"`

	// nodeUID identifies the Node whose current key verified the receipt.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Type=string
	NodeUID types.UID `json:"nodeUID"`

	// containerID identifies the retained application container.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=256
	ContainerID string `json:"containerID"`

	// taskStartTime distinguishes the retained task from PID reuse or restart.
	// +required
	// +kubebuilder:validation:Minimum=1
	TaskStartTime int64 `json:"taskStartTime"`

	// runtimeIncarnation identifies the native runtime instance that verified execution.
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	RuntimeIncarnation string `json:"runtimeIncarnation"`

	// targetActivationID identifies the current successor binding.
	// +required
	TargetActivationID RuntimeAdoptionID `json:"targetActivationID"`

	// receiptDigest identifies the current verified target receipt.
	// +required
	ReceiptDigest RuntimeAdoptionDigest `json:"receiptDigest"`

	// contextDigest binds the receipt to this exact adoption context.
	// +required
	ContextDigest RuntimeAdoptionDigest `json:"contextDigest"`

	// commitDigest identifies the confirmed runtime release observation.
	// +required
	CommitDigest RuntimeAdoptionDigest `json:"commitDigest"`

	// policyEpoch is the exact prepared policy epoch, not an API resource version.
	// +required
	// +kubebuilder:validation:Minimum=0
	PolicyEpoch int64 `json:"policyEpoch"`

	// validUntil bounds the current observational evidence, not the historical commit.
	// +required
	ValidUntil metav1.Time `json:"validUntil"`

	// conditions report the current verification result.
	// +optional
	// +listType=map
	// +listMapKey=type
	// +kubebuilder:validation:MaxItems=16
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}
