apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: ${WARM_POOL_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${WARM_POOL_NAME}
spec:
  replicas: 0
  sandboxTemplateRef:
    name: ${TEMPLATE_NAME}
