#!/usr/bin/env bash
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# File is initially implemented as a no-op so that a presubmit prowjob can safely
# be added without any disruption. Once the presubmit is added, a subsequent PR
# can actually invoke the unit tests (e.g. go test).
echo "TODO: replace this with unit test invocation once unit tests are confirmed passing"
