# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: watcher/v1/watcher.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'watcher/v1/watcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18watcher/v1/watcher.proto\x12\nwatcher.v1\"C\n\x0fWatchDirRequest\x12\x12\n\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n\trecursive\x18\x02 \x01(\x08R\trecursive\"\x7f\n\tFileEvent\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x19.watcher.v1.FileEventTypeR\x04type\x12\x12\n\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n\x08old_path\x18\x03 \x01(\tR\x07oldPath\x12\x14\n\x05\x65rror\x18\x04 \x01(\tR\x05\x65rror*\xd5\x01\n\rFileEventType\x12\x1f\n\x1b\x46ILE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x46ILE_EVENT_TYPE_CREATE\x10\x01\x12\x19\n\x15\x46ILE_EVENT_TYPE_WRITE\x10\x02\x12\x1a\n\x16\x46ILE_EVENT_TYPE_REMOVE\x10\x03\x12\x1a\n\x16\x46ILE_EVENT_TYPE_RENAME\x10\x04\x12\x19\n\x15\x46ILE_EVENT_TYPE_CHMOD\x10\x05\x12\x19\n\x15\x46ILE_EVENT_TYPE_ERROR\x10\x06\x32V\n\x12\x46ileWatcherService\x12@\n\x08WatchDir\x12\x1b.watcher.v1.WatchDirRequest\x1a\x15.watcher.v1.FileEvent0\x01\x42\xae\x01\n\x0e\x63om.watcher.v1B\x0cWatcherProtoP\x01ZEsigs.k8s.io/agent-sandbox/packages/sandboxd/spec/watcher/v1;watcherv1\xa2\x02\x03WXX\xaa\x02\nWatcher.V1\xca\x02\nWatcher\\V1\xe2\x02\x16Watcher\\V1\\GPBMetadata\xea\x02\x0bWatcher::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watcher.v1.watcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.watcher.v1B\014WatcherProtoP\001ZEsigs.k8s.io/agent-sandbox/packages/sandboxd/spec/watcher/v1;watcherv1\242\002\003WXX\252\002\nWatcher.V1\312\002\nWatcher\\V1\342\002\026Watcher\\V1\\GPBMetadata\352\002\013Watcher::V1'
  _globals['_FILEEVENTTYPE']._serialized_start=239
  _globals['_FILEEVENTTYPE']._serialized_end=452
  _globals['_WATCHDIRREQUEST']._serialized_start=40
  _globals['_WATCHDIRREQUEST']._serialized_end=107
  _globals['_FILEEVENT']._serialized_start=109
  _globals['_FILEEVENT']._serialized_end=236
  _globals['_FILEWATCHERSERVICE']._serialized_start=454
  _globals['_FILEWATCHERSERVICE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
