# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from watcher.v1 import watcher_pb2 as watcher_dot_v1_dot_watcher__pb2


class FileWatcherServiceStub:
    """FileWatcherService provides real-time filesystem event streaming
    for directories within the sandbox. Events are delivered via
    server-side streaming gRPC, allowing AI agents and other clients
    to react immediately to file changes without polling.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchDir = channel.unary_stream(
                '/watcher.v1.FileWatcherService/WatchDir',
                request_serializer=watcher_dot_v1_dot_watcher__pb2.WatchDirRequest.SerializeToString,
                response_deserializer=watcher_dot_v1_dot_watcher__pb2.FileEvent.FromString,
                _registered_method=True)


class FileWatcherServiceServicer:
    """FileWatcherService provides real-time filesystem event streaming
    for directories within the sandbox. Events are delivered via
    server-side streaming gRPC, allowing AI agents and other clients
    to react immediately to file changes without polling.
    """

    def WatchDir(self, request, context):
        """WatchDir streams filesystem events (create, write, remove, rename,
        chmod) for the given directory. The stream remains open until the
        client disconnects or the watched directory is removed.

        Events are debounced (~250ms) to coalesce bursts from atomic writes
        (temp-file + rename). Each event path is re-validated against the
        sandbox root on delivery to prevent symlink-swap escapes.

        Errors that terminate the watch (e.g. directory removed) are surfaced
        as a final FileEvent with type ERROR before the stream closes, rather
        than as a gRPC status code, so clients can distinguish transient
        transport failures from intentional termination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileWatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchDir': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchDir,
                    request_deserializer=watcher_dot_v1_dot_watcher__pb2.WatchDirRequest.FromString,
                    response_serializer=watcher_dot_v1_dot_watcher__pb2.FileEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'watcher.v1.FileWatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('watcher.v1.FileWatcherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileWatcherService:
    """FileWatcherService provides real-time filesystem event streaming
    for directories within the sandbox. Events are delivered via
    server-side streaming gRPC, allowing AI agents and other clients
    to react immediately to file changes without polling.
    """

    @staticmethod
    def WatchDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/watcher.v1.FileWatcherService/WatchDir',
            watcher_dot_v1_dot_watcher__pb2.WatchDirRequest.SerializeToString,
            watcher_dot_v1_dot_watcher__pb2.FileEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
