// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SandboxListerExpansion allows custom methods to be added to
// SandboxLister.
type SandboxListerExpansion interface{}

// SandboxNamespaceListerExpansion allows custom methods to be added to
// SandboxNamespaceLister.
type SandboxNamespaceListerExpansion interface{}
