// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apiv1alpha1 "sigs.k8s.io/agent-sandbox/api/v1alpha1"
)

// SandboxLister helps list Sandboxes.
// All objects returned here must be treated as read-only.
type SandboxLister interface {
	// List lists all Sandboxes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.Sandbox, err error)
	// Sandboxes returns an object that can list and get Sandboxes.
	Sandboxes(namespace string) SandboxNamespaceLister
	SandboxListerExpansion
}

// sandboxLister implements the SandboxLister interface.
type sandboxLister struct {
	listers.ResourceIndexer[*apiv1alpha1.Sandbox]
}

// NewSandboxLister returns a new SandboxLister.
func NewSandboxLister(indexer cache.Indexer) SandboxLister {
	return &sandboxLister{listers.New[*apiv1alpha1.Sandbox](indexer, apiv1alpha1.Resource("sandbox"))}
}

// Sandboxes returns an object that can list and get Sandboxes.
func (s *sandboxLister) Sandboxes(namespace string) SandboxNamespaceLister {
	return sandboxNamespaceLister{listers.NewNamespaced[*apiv1alpha1.Sandbox](s.ResourceIndexer, namespace)}
}

// SandboxNamespaceLister helps list and get Sandboxes.
// All objects returned here must be treated as read-only.
type SandboxNamespaceLister interface {
	// List lists all Sandboxes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.Sandbox, err error)
	// Get retrieves the Sandbox from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.Sandbox, error)
	SandboxNamespaceListerExpansion
}

// sandboxNamespaceLister implements the SandboxNamespaceLister
// interface.
type sandboxNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.Sandbox]
}
