// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agentsandbox/worker/v1/worker.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pid   int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// start_time_unix_micros is the worker process's start time in Unix
	// microseconds. Stable across the worker's lifetime; changes only after
	// a restart.
	StartTimeUnixMicros int64 `protobuf:"varint,2,opt,name=start_time_unix_micros,json=startTimeUnixMicros,proto3" json:"start_time_unix_micros,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PingResponse) GetStartTimeUnixMicros() int64 {
	if x != nil {
		return x.StartTimeUnixMicros
	}
	return 0
}

type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// argv[0] is the program to run; argv[1..] are its arguments. The
	// worker performs no shell parsing.
	Argv []string `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	// env is appended to the worker's own environment. Keys here override
	// the inherited values.
	Env map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// cwd is the working directory inside the sandbox. Empty means use the
	// worker's cwd (typically the workspace mount path).
	Cwd           string `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	//	*ExecResponse_Exit
	Kind          isExecResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ExecResponse) GetKind() isExecResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Kind.(*ExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Kind.(*ExecResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecResponse) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Kind.(*ExecResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecResponse_Kind interface {
	isExecResponse_Kind()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecResponse_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecResponse_Stdout) isExecResponse_Kind() {}

func (*ExecResponse_Stderr) isExecResponse_Kind() {}

func (*ExecResponse_Exit) isExecResponse_Kind() {}

type ExecExit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code is the process exit code. -1 means the process was killed
	// by a signal (see `signal`).
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// signal is the terminating signal number, or 0 if the process exited
	// normally.
	Signal        int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecExit) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

// OpenShellRequest is the client→worker direction of the OpenShell bidi
// stream. The first frame on the stream MUST set `start`; subsequent
// frames carry stdin bytes or window resizes.
type OpenShellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*OpenShellRequest_Start
	//	*OpenShellRequest_Stdin
	//	*OpenShellRequest_Resize
	//	*OpenShellRequest_Eof
	Kind          isOpenShellRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenShellRequest) Reset() {
	*x = OpenShellRequest{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShellRequest) ProtoMessage() {}

func (x *OpenShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShellRequest.ProtoReflect.Descriptor instead.
func (*OpenShellRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *OpenShellRequest) GetKind() isOpenShellRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *OpenShellRequest) GetStart() *OpenShellStart {
	if x != nil {
		if x, ok := x.Kind.(*OpenShellRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *OpenShellRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Kind.(*OpenShellRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *OpenShellRequest) GetResize() *OpenShellResize {
	if x != nil {
		if x, ok := x.Kind.(*OpenShellRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *OpenShellRequest) GetEof() bool {
	if x != nil {
		if x, ok := x.Kind.(*OpenShellRequest_Eof); ok {
			return x.Eof
		}
	}
	return false
}

type isOpenShellRequest_Kind interface {
	isOpenShellRequest_Kind()
}

type OpenShellRequest_Start struct {
	Start *OpenShellStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type OpenShellRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type OpenShellRequest_Resize struct {
	Resize *OpenShellResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type OpenShellRequest_Eof struct {
	// eof closes the slave's stdin side. The shell typically exits soon
	// after.
	Eof bool `protobuf:"varint,4,opt,name=eof,proto3,oneof"`
}

func (*OpenShellRequest_Start) isOpenShellRequest_Kind() {}

func (*OpenShellRequest_Stdin) isOpenShellRequest_Kind() {}

func (*OpenShellRequest_Resize) isOpenShellRequest_Kind() {}

func (*OpenShellRequest_Eof) isOpenShellRequest_Kind() {}

type OpenShellStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// argv to exec inside the sandbox. Empty → use `["/bin/bash","-l"]`.
	Argv []string `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	// env entries to set/override (PATH, TERM, etc.).
	Env map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// cwd to chdir into before exec. Empty → worker's cwd.
	Cwd string `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Initial PTY size. 0/0 → use kernel defaults.
	Cols          uint32 `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32 `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenShellStart) Reset() {
	*x = OpenShellStart{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenShellStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShellStart) ProtoMessage() {}

func (x *OpenShellStart) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShellStart.ProtoReflect.Descriptor instead.
func (*OpenShellStart) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *OpenShellStart) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *OpenShellStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *OpenShellStart) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *OpenShellStart) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *OpenShellStart) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type OpenShellResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenShellResize) Reset() {
	*x = OpenShellResize{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenShellResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShellResize) ProtoMessage() {}

func (x *OpenShellResize) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShellResize.ProtoReflect.Descriptor instead.
func (*OpenShellResize) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *OpenShellResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *OpenShellResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// OpenShellResponse is the worker→client direction of the bidi stream.
type OpenShellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*OpenShellResponse_Stdout
	//	*OpenShellResponse_Stderr
	//	*OpenShellResponse_Exit
	Kind          isOpenShellResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenShellResponse) Reset() {
	*x = OpenShellResponse{}
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShellResponse) ProtoMessage() {}

func (x *OpenShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_worker_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShellResponse.ProtoReflect.Descriptor instead.
func (*OpenShellResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_worker_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *OpenShellResponse) GetKind() isOpenShellResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *OpenShellResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Kind.(*OpenShellResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *OpenShellResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Kind.(*OpenShellResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *OpenShellResponse) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Kind.(*OpenShellResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isOpenShellResponse_Kind interface {
	isOpenShellResponse_Kind()
}

type OpenShellResponse_Stdout struct {
	// Stdout and stderr are merged into `stdout` because the shell's
	// controlling tty unifies them; `stderr` is reserved for future
	// non-PTY exec.
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type OpenShellResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type OpenShellResponse_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*OpenShellResponse_Stdout) isOpenShellResponse_Kind() {}

func (*OpenShellResponse_Stderr) isOpenShellResponse_Kind() {}

func (*OpenShellResponse_Exit) isOpenShellResponse_Kind() {}

var File_agentsandbox_worker_v1_worker_proto protoreflect.FileDescriptor

const file_agentsandbox_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"#agentsandbox/worker/v1/worker.proto\x12\x16agentsandbox.worker.v1\"\r\n" +
	"\vPingRequest\"U\n" +
	"\fPingResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x123\n" +
	"\x16start_time_unix_micros\x18\x02 \x01(\x03R\x13startTimeUnixMicros\"\xab\x01\n" +
	"\vExecRequest\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12>\n" +
	"\x03env\x18\x02 \x03(\v2,.agentsandbox.worker.v1.ExecRequest.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\fExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x126\n" +
	"\x04exit\x18\x03 \x01(\v2 .agentsandbox.worker.v1.ExecExitH\x00R\x04exitB\x06\n" +
	"\x04kind\"?\n" +
	"\bExecExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\"\xc9\x01\n" +
	"\x10OpenShellRequest\x12>\n" +
	"\x05start\x18\x01 \x01(\v2&.agentsandbox.worker.v1.OpenShellStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12A\n" +
	"\x06resize\x18\x03 \x01(\v2'.agentsandbox.worker.v1.OpenShellResizeH\x00R\x06resize\x12\x12\n" +
	"\x03eof\x18\x04 \x01(\bH\x00R\x03eofB\x06\n" +
	"\x04kind\"\xd9\x01\n" +
	"\x0eOpenShellStart\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12A\n" +
	"\x03env\x18\x02 \x03(\v2/.agentsandbox.worker.v1.OpenShellStart.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\rR\x04rows\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x0fOpenShellResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x87\x01\n" +
	"\x11OpenShellResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x126\n" +
	"\x04exit\x18\x03 \x01(\v2 .agentsandbox.worker.v1.ExecExitH\x00R\x04exitB\x06\n" +
	"\x04kind2\x9d\x02\n" +
	"\rWorkerService\x12Q\n" +
	"\x04Ping\x12#.agentsandbox.worker.v1.PingRequest\x1a$.agentsandbox.worker.v1.PingResponse\x12S\n" +
	"\x04Exec\x12#.agentsandbox.worker.v1.ExecRequest\x1a$.agentsandbox.worker.v1.ExecResponse0\x01\x12d\n" +
	"\tOpenShell\x12(.agentsandbox.worker.v1.OpenShellRequest\x1a).agentsandbox.worker.v1.OpenShellResponse(\x010\x01B\xe6\x01\n" +
	"\x1acom.agentsandbox.worker.v1B\vWorkerProtoP\x01ZAsigs.k8s.io/agent-sandbox/clients/agentsandbox/worker/v1;workerv1\xa2\x02\x03AWX\xaa\x02\x16Agentsandbox.Worker.V1\xca\x02\x16Agentsandbox\\Worker\\V1\xe2\x02\"Agentsandbox\\Worker\\V1\\GPBMetadata\xea\x02\x18Agentsandbox::Worker::V1b\x06proto3"

var (
	file_agentsandbox_worker_v1_worker_proto_rawDescOnce sync.Once
	file_agentsandbox_worker_v1_worker_proto_rawDescData []byte
)

func file_agentsandbox_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_agentsandbox_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_agentsandbox_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentsandbox_worker_v1_worker_proto_rawDesc), len(file_agentsandbox_worker_v1_worker_proto_rawDesc)))
	})
	return file_agentsandbox_worker_v1_worker_proto_rawDescData
}

var file_agentsandbox_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agentsandbox_worker_v1_worker_proto_goTypes = []any{
	(*PingRequest)(nil),       // 0: agentsandbox.worker.v1.PingRequest
	(*PingResponse)(nil),      // 1: agentsandbox.worker.v1.PingResponse
	(*ExecRequest)(nil),       // 2: agentsandbox.worker.v1.ExecRequest
	(*ExecResponse)(nil),      // 3: agentsandbox.worker.v1.ExecResponse
	(*ExecExit)(nil),          // 4: agentsandbox.worker.v1.ExecExit
	(*OpenShellRequest)(nil),  // 5: agentsandbox.worker.v1.OpenShellRequest
	(*OpenShellStart)(nil),    // 6: agentsandbox.worker.v1.OpenShellStart
	(*OpenShellResize)(nil),   // 7: agentsandbox.worker.v1.OpenShellResize
	(*OpenShellResponse)(nil), // 8: agentsandbox.worker.v1.OpenShellResponse
	nil,                       // 9: agentsandbox.worker.v1.ExecRequest.EnvEntry
	nil,                       // 10: agentsandbox.worker.v1.OpenShellStart.EnvEntry
}
var file_agentsandbox_worker_v1_worker_proto_depIdxs = []int32{
	9,  // 0: agentsandbox.worker.v1.ExecRequest.env:type_name -> agentsandbox.worker.v1.ExecRequest.EnvEntry
	4,  // 1: agentsandbox.worker.v1.ExecResponse.exit:type_name -> agentsandbox.worker.v1.ExecExit
	6,  // 2: agentsandbox.worker.v1.OpenShellRequest.start:type_name -> agentsandbox.worker.v1.OpenShellStart
	7,  // 3: agentsandbox.worker.v1.OpenShellRequest.resize:type_name -> agentsandbox.worker.v1.OpenShellResize
	10, // 4: agentsandbox.worker.v1.OpenShellStart.env:type_name -> agentsandbox.worker.v1.OpenShellStart.EnvEntry
	4,  // 5: agentsandbox.worker.v1.OpenShellResponse.exit:type_name -> agentsandbox.worker.v1.ExecExit
	0,  // 6: agentsandbox.worker.v1.WorkerService.Ping:input_type -> agentsandbox.worker.v1.PingRequest
	2,  // 7: agentsandbox.worker.v1.WorkerService.Exec:input_type -> agentsandbox.worker.v1.ExecRequest
	5,  // 8: agentsandbox.worker.v1.WorkerService.OpenShell:input_type -> agentsandbox.worker.v1.OpenShellRequest
	1,  // 9: agentsandbox.worker.v1.WorkerService.Ping:output_type -> agentsandbox.worker.v1.PingResponse
	3,  // 10: agentsandbox.worker.v1.WorkerService.Exec:output_type -> agentsandbox.worker.v1.ExecResponse
	8,  // 11: agentsandbox.worker.v1.WorkerService.OpenShell:output_type -> agentsandbox.worker.v1.OpenShellResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agentsandbox_worker_v1_worker_proto_init() }
func file_agentsandbox_worker_v1_worker_proto_init() {
	if File_agentsandbox_worker_v1_worker_proto != nil {
		return
	}
	file_agentsandbox_worker_v1_worker_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
		(*ExecResponse_Exit)(nil),
	}
	file_agentsandbox_worker_v1_worker_proto_msgTypes[5].OneofWrappers = []any{
		(*OpenShellRequest_Start)(nil),
		(*OpenShellRequest_Stdin)(nil),
		(*OpenShellRequest_Resize)(nil),
		(*OpenShellRequest_Eof)(nil),
	}
	file_agentsandbox_worker_v1_worker_proto_msgTypes[8].OneofWrappers = []any{
		(*OpenShellResponse_Stdout)(nil),
		(*OpenShellResponse_Stderr)(nil),
		(*OpenShellResponse_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentsandbox_worker_v1_worker_proto_rawDesc), len(file_agentsandbox_worker_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentsandbox_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_agentsandbox_worker_v1_worker_proto_depIdxs,
		MessageInfos:      file_agentsandbox_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_agentsandbox_worker_v1_worker_proto = out.File
	file_agentsandbox_worker_v1_worker_proto_goTypes = nil
	file_agentsandbox_worker_v1_worker_proto_depIdxs = nil
}
