// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	apiv1beta1 "sigs.k8s.io/agent-sandbox/api/v1beta1"
)

// PodFailurePolicyApplyConfiguration represents a declarative configuration of the PodFailurePolicy type for use
// with apply.
//
// PodFailurePolicy describes how the Sandbox handles a Failed backing Pod.
type PodFailurePolicyApplyConfiguration struct {
	// action determines whether the Failed Pod is left in place or replaced.
	Action *apiv1beta1.PodFailurePolicyAction `json:"action,omitempty"`
}

// PodFailurePolicyApplyConfiguration constructs a declarative configuration of the PodFailurePolicy type for use with
// apply.
func PodFailurePolicy() *PodFailurePolicyApplyConfiguration {
	return &PodFailurePolicyApplyConfiguration{}
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *PodFailurePolicyApplyConfiguration) WithAction(value apiv1beta1.PodFailurePolicyAction) *PodFailurePolicyApplyConfiguration {
	b.Action = &value
	return b
}
