// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SandboxLifecycleStatusApplyConfiguration represents a declarative configuration of the SandboxLifecycleStatus type for use
// with apply.
//
// SandboxLifecycleStatus stores controller-observed lifecycle timestamps and
// metric dedupe state for a Sandbox.
type SandboxLifecycleStatusApplyConfiguration struct {
	// firstObservedTime is when the controller first observed this Sandbox.
	FirstObservedTime *v1.Time `json:"firstObservedTime,omitempty"`
	// recordedStages lists Ready-path stages whose latency has already been
	// accounted for. Each value is recorded at most once, including warm or
	// pre-existing stages that are marked recorded without a histogram sample.
	RecordedStages []string `json:"recordedStages,omitempty"`
}

// SandboxLifecycleStatusApplyConfiguration constructs a declarative configuration of the SandboxLifecycleStatus type for use with
// apply.
func SandboxLifecycleStatus() *SandboxLifecycleStatusApplyConfiguration {
	return &SandboxLifecycleStatusApplyConfiguration{}
}

// WithFirstObservedTime sets the FirstObservedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirstObservedTime field is set to the value of the last call.
func (b *SandboxLifecycleStatusApplyConfiguration) WithFirstObservedTime(value v1.Time) *SandboxLifecycleStatusApplyConfiguration {
	b.FirstObservedTime = &value
	return b
}

// WithRecordedStages adds the given value to the RecordedStages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RecordedStages field.
func (b *SandboxLifecycleStatusApplyConfiguration) WithRecordedStages(values ...string) *SandboxLifecycleStatusApplyConfiguration {
	for i := range values {
		b.RecordedStages = append(b.RecordedStages, values[i])
	}
	return b
}
