#!/usr/bin/env python3
# Copyright 2026 The Kubernetes Authors.
# Licensed under the Apache License, Version 2.0.
#
# Generate hub RBAC for fleet members publishing ClusterProfile status.
#
# The rule that matters is `resourceNames`. Without it, any member could
# publish capacity for any cluster in the fleet -- and since the planner
# derives placement weights from those properties, a single compromised or
# buggy member could quietly redirect the whole fleet's workload to itself by
# publishing a huge sandbox-capacity. Per-member Roles keyed on resourceNames
# make that impossible to express.
#
# Note `clusterprofiles/status` and NOT `clusterprofiles`: members write status
# only. Creating the objects and owning spec/conditions is the cluster
# manager's job. A member that could create ClusterProfiles could invent
# clusters that do not exist.
#
#   ./deploy/gen-hub-rbac.py --project my-project > /tmp/hub-rbac.yaml
#   kubectl --context <HUB> apply -f /tmp/hub-rbac.yaml
#
# Subjects are GCP service account emails because GKE maps IAM identities onto
# RBAC `User` subjects by email. On a non-GKE hub, switch --subject-kind to
# ServiceAccount.

from __future__ import annotations

import argparse
import sys

DEFAULT_CLUSTERS = [f"cluster-{c}" for c in "abcdef"]

ROLE = """---
# {cluster}: may publish its OWN capacity, nothing else.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-member-{cluster}
  namespace: {namespace}
rules:
  - apiGroups: ["multicluster.x-k8s.io"]
    resources: ["clusterprofiles/status"]
    resourceNames: ["{cluster}"]
    verbs: ["get", "patch"]
  # Read access to the object itself is needed for SSA to resolve conflicts.
  # Deliberately NOT namespace-wide: a member has no reason to enumerate its
  # peers, and fleet-wide read is how a member learns what to impersonate.
  - apiGroups: ["multicluster.x-k8s.io"]
    resources: ["clusterprofiles"]
    resourceNames: ["{cluster}"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-member-{cluster}
  namespace: {namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-member-{cluster}
subjects:
  - kind: {subject_kind}
    name: {subject}
{subject_extra}"""

# The planner reads every profile, so it gets one namespace-wide read Role.
PLANNER = """---
# The planner/`fleetctl` side: reads the whole inventory, writes nothing.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-planner
  namespace: {namespace}
rules:
  - apiGroups: ["multicluster.x-k8s.io"]
    resources: ["clusterprofiles"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-planner
  namespace: {namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-planner
subjects:
  - kind: {subject_kind}
    name: {planner_subject}
{subject_extra}"""


def main() -> int:
  p = argparse.ArgumentParser(description=__doc__)
  p.add_argument("--namespace", default="fleet-system")
  p.add_argument("--clusters", nargs="*", default=DEFAULT_CLUSTERS)
  p.add_argument("--project", help="GCP project, for the default GSA emails")
  p.add_argument("--subject-kind", default="User",
                 choices=["User", "ServiceAccount"],
                 help="GKE maps IAM identities to User-by-email; use "
                      "ServiceAccount on a non-GKE hub")
  p.add_argument("--sa-namespace", default="fleet-system",
                 help="Namespace of the subject when --subject-kind=ServiceAccount")
  p.add_argument("--subject-template",
                 help="Override, e.g. 'fleet-{cluster}@proj.iam.gserviceaccount.com'")
  p.add_argument("--planner-subject",
                 help="Identity running fleetctl (default: fleet-planner@...)")
  args = p.parse_args()

  if args.subject_template:
    tmpl = args.subject_template
  elif args.subject_kind == "User":
    if not args.project:
      sys.exit("--project is required for GSA emails "
               "(or pass --subject-template)")
    tmpl = "fleet-member-{cluster}@" + args.project + ".iam.gserviceaccount.com"
  else:
    tmpl = "fleet-member-{cluster}"

  planner = args.planner_subject or (
      tmpl.replace("fleet-member-{cluster}", "fleet-planner"))

  extra = (f"    namespace: {args.sa_namespace}\n"
           if args.subject_kind == "ServiceAccount" else "")

  print("# Generated by deploy/gen-hub-rbac.py -- apply to the HUB cluster.")
  for cluster in args.clusters:
    print(ROLE.format(cluster=cluster, namespace=args.namespace,
                      subject_kind=args.subject_kind,
                      subject=tmpl.format(cluster=cluster),
                      subject_extra=extra), end="")
  print(PLANNER.format(namespace=args.namespace,
                       subject_kind=args.subject_kind,
                       planner_subject=planner,
                       subject_extra=extra), end="")
  return 0


if __name__ == "__main__":
  sys.exit(main())
