#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import json
import os
import subprocess

from shared import utils


def main(args):
    repo_root = utils.get_repo_root()
    helm_dir = os.path.join(repo_root, "helm")

    image_prefix = utils.get_image_prefix(args)
    image_tag = args.image_tag or utils.get_image_tag()
    image_repository = f"{image_prefix}agent-sandbox-controller"

    helm_cmd = [
        "helm", "upgrade", "--install", "agent-sandbox", helm_dir,
        "--namespace", "agent-sandbox-system",
        "--create-namespace",
        "--set", f"image.repository={image_repository}",
        "--set", f"image.tag={image_tag}",
    ]

    if args.extensions:
        helm_cmd += ["--set", "controller.extensions=true"]

    if args.controller_args:
        extra_args = args.controller_args.split()
        helm_cmd += ["--set-json", f"controller.extraArgs={json.dumps(extra_args)}"]

    print(f"Running: {' '.join(helm_cmd)}")
    subprocess.run(helm_cmd, cwd=repo_root, check=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Deploy agent-sandbox using Helm")
    parser.add_argument("--image-prefix",
                        dest="image_prefix",
                        help="prefix for the image name. requires slash at the end if a path",
                        type=str,
                        default=os.getenv("IMAGE_PREFIX"))
    parser.add_argument("--image-tag",
                        dest="image_tag",
                        help="Image tag for this build. If not set, a default tag is generated based on date and git commit",
                        type=str,
                        default=os.getenv("IMAGE_TAG"))
    parser.add_argument("--extensions",
                        action="store_true",
                        help="Enable the extensions controller. Sets controller.extensions=true in Helm values.")
    parser.add_argument("--controller-args",
                        dest="controller_args",
                        help="Space-separated flags to pass to the controller as extraArgs. Example: "
                             "--controller-args \"--enable-pprof-debug --zap-log-level=debug\".",
                        type=str,
                        default="")
    args = parser.parse_args()
    main(args)
