#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import os
import subprocess
import sys
import argparse

script_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(script_dir)

from shared import utils

def main():
    # Find the repo root from the script's location
    # parse arguments and call
    parser = argparse.ArgumentParser(description="run go generate")
    parser.add_argument("--working-dir",
                        dest="working_dir",
                        help="use working dir instead of repo root",
                        type=str,
                        default=None)
    args = parser.parse_args()

    working_dir = args.working_dir or utils.get_repo_root()
    print(f"using working dir: {working_dir}")
    utils.check_go_command(["go", "generate", "-v", "./..."], cwd=working_dir)

if __name__ == "__main__":
    main()
