#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import subprocess
import json

from shared import utils
from shared import golang


def create_buildx_builder_if_not_exists():
    builder_name = "agent-sandbox-builder"
    try:
        subprocess.run(
            ["docker", "buildx", "inspect", builder_name],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"buildx builder '{builder_name}' already exists.")
    except subprocess.CalledProcessError:
        print(f"creating buildx builder '{builder_name}'.")
        subprocess.run(
            ["docker", "buildx", "create", "--name", builder_name], check=True
        )
    subprocess.run(["docker", "buildx", "use", builder_name], check=True)


def build_and_push_image_with_docker_buildx(
    args, service_name, srcdir, dockerfile_path
):
    platforms = "linux/amd64,linux/arm64"
    build_cmd = [
        "docker",
        "buildx",
        "build",
        "--progress=plain",
        f"--output=type={args.docker_build_output_type}",
    ]
    if args.docker_build_output_type == "registry":
        build_cmd.append("--platform=" + platforms)
    image_name = utils.get_full_image_name(args, service_name)
    build_cmd.extend(["-t", image_name])
    for tag in args.extra_image_tags:  # additional image tags
        extra_tag = utils.get_full_image_name(args, service_name, tag=tag)
        build_cmd.extend(["-t", extra_tag])
    build_cmd.extend(
        [
            "-f",
            dockerfile_path,
            ".",
        ]
    )
    subprocess.run(build_cmd, cwd=srcdir, check=True)
    print(f"pushed image {image_name}")


def load_kind_image(cluster_name, service_name, srcdir):
    image_name = utils.get_full_image_name(args, service_name)
    build_cmd = [
        "kind",
        "load",
        "docker-image",
        f"--name={cluster_name}",
        image_name,
    ]

    subprocess.run(build_cmd, cwd=srcdir, check=True)
    print(f"loaded image {image_name} into kind cluster {args.kind_cluster_name}")


def build_and_push_image(args, service_name, srcdir, dockerfile_path):
    build_and_push_image_with_docker_buildx(args, service_name, srcdir, dockerfile_path)
    if args.kind_cluster_name:
        load_kind_image(args.kind_cluster_name, service_name, srcdir)


def find_dockerfiles(repo_root):
    """Finds all Dockerfiles to be built."""
    dockerfiles = []

    # Go module images
    def find_go_mod_dockerfiles(mod_dir):
        images_dir = os.path.join(mod_dir, "images")
        if not os.path.isdir(images_dir):
            return
        for root, dirs, files in os.walk(images_dir):
            for filename in files:
                if filename == "Dockerfile":
                    dockerfile_path = os.path.join(root, filename)
                    service_name = os.path.basename(root)
                    dockerfiles.append((service_name, mod_dir, dockerfile_path))

    golang.for_each_module(find_go_mod_dockerfiles)

    # Example images
    examples_dir = os.path.join(repo_root, "examples")
    if os.path.isdir(examples_dir):
        for example in os.listdir(examples_dir):
            example_dir = os.path.join(examples_dir, example)
            if not os.path.isdir(example_dir):
                continue
            dockerfile_path = os.path.join(example_dir, "Dockerfile")
            if os.path.isfile(dockerfile_path):
                service_name = example
                dockerfiles.append((service_name, example_dir, dockerfile_path))

    # Python SDK image
    python_sdk_dir = os.path.join(
        repo_root, "clients", "python", "agentic-sandbox-client", "sandbox_router"
    )
    dockerfile_path = os.path.join(python_sdk_dir, "Dockerfile")
    if os.path.isfile(dockerfile_path):
        service_name = "sandbox-router"
        dockerfiles.append((service_name, python_sdk_dir, dockerfile_path))

    return dockerfiles


def main(args):
    """Builds and pushes docker images."""
    repo_root = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )

    images_json_path = os.path.join(repo_root, "dev/tools/shared/images.json")
    if not os.path.isfile(images_json_path):
        print(f"Error: images.json not found at {images_json_path}")

    with open(images_json_path, "r") as f:
        images_to_build = json.load(f)

    create_buildx_builder_if_not_exists()

    for image_info in images_to_build:
        service_name = image_info["service_name"]
        context_dir = image_info["context_dir"]
        dockerfile_path = os.path.join(context_dir, service_name, "Dockerfile")

        build_context_abs = os.path.join(repo_root, context_dir, service_name)
        dockerfile_path_abs = os.path.join(repo_root, dockerfile_path)

        if not service_name:
            service_name = "agent-sandbox-controller"
        print(
            f"building image for {service_name} from {dockerfile_path_abs} in {build_context_abs}"
        )
        build_and_push_image(args, service_name, build_context_abs, dockerfile_path_abs)


if __name__ == "__main__":
    # parse arguments and call
    parser = argparse.ArgumentParser(description="Build and push Docker images")
    parser.add_argument(
        "--image-prefix",
        dest="image_prefix",
        help="Prefix for the image name. requires slash at the end if a path",
        type=str,
        default=os.getenv("IMAGE_PREFIX"),
    )
    parser.add_argument(
        "--extra-image-tag",
        dest="extra_image_tags",
        help="Additional tags to use when publishing images.",
        type=str,
        action="append",
        default=[],
    )
    parser.add_argument(
        "--kind-cluster-name",
        dest="kind_cluster_name",
        help="Name of the kind cluster. If set, images will be loaded into the cluster",
        type=str,
        default=os.getenv("KIND_CLUSTER_NAME"),
    )
    args = parser.parse_args()

    if args.kind_cluster_name:
        args.docker_build_output_type = "docker"
    else:
        args.docker_build_output_type = "registry"

    main(args)
