apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  # The test_client.py expects the template to have this name
  name: python-sandbox-template
  namespace: default
spec:
  podTemplate:
    spec:
      # Optional, must have gVisor enabled node
      runtimeClassName: gvisor
      containers:
      - name: python-runtime
        # The test_client.py expects the image to be agent-sandbox/examples/python-runtime-sandbox
        # sed -i "s|IMAGE_PLACEHOLDER|${PYTHON_RUNTIME_SANDBOX_IMG}|g" python-sandbox-template.yaml
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: "/"
            port: 8888
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
      restartPolicy: "OnFailure"