# Warmpool Template
apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: {{.Name}}
spec:
  replicas: {{.Replicas}}
  sandboxTemplateRef:
    name: {{.TemplateName}}
