apiVersion: v1
kind: Namespace
metadata:
  name: tenant-a
  labels:
    agents.x-k8s.io/auto-suspension: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-b
  labels:
    agents.x-k8s.io/auto-suspension: "enabled"
