apiVersion: agents.x-k8s.io/v1beta1
kind: Sandbox
metadata:
  name: sandbox-b1
  namespace: tenant-b
spec:
  operatingMode: Suspended
  service: true
  podTemplate:
    spec:
      containers:
      - name: web
        image: hashicorp/http-echo:latest
        args:
        - "-text=Hello from Tenant-B Sandbox-B1 Container!"
        ports:
        - containerPort: 5678
