/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This smoke test proves that a Connect-ES client generated by protoc-gen-es
// from packages/sandboxd/spec/process/v1/process.proto can complete a real
// gRPC Execute call over h2c through a Kubernetes WebSocket pod port-forward.
// The production PodTunnel, including its lifecycle and backpressure behavior,
// lands with the connect layer in a follow-up PR and is tested there.
//
// It imports the generated stub via a relative path into the SDK's source
// tree (rather than through the published package) because src/_proto is
// deliberately excluded from the SDK's tsc build while nothing in the
// public API references it yet (see src/_proto/README.md).

import * as net from "node:net";
import { Writable } from "node:stream";
import { create } from "@bufbuild/protobuf";
import { createClient } from "@connectrpc/connect";
import { createGrpcTransport } from "@connectrpc/connect-node";
import * as k8s from "@kubernetes/client-node";
import {
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  test,
} from "vitest";
import {
  ExecuteRequestSchema,
  ProcessConfigSchema,
  ProcessService,
} from "../../../../clients/typescript/agentic-sandbox-client/src/_proto/process/v1/process_pb.js";
import { TestContext } from "./framework/context.js";
import { readyConditionIsTrue } from "./framework/predicates.js";

const SANDBOX_NAME = "sandbox-sandboxd-interop";

// Mirrors test/e2e/extensions/sandboxd_test.go's sandboxdManifest: sandboxd
// as the sole container, binding 0.0.0.0 (the daemon default) so the
// kubelet readiness probe and the port-forward both reach it.
const SANDBOXD_MANIFEST = `
apiVersion: agents.x-k8s.io/v1beta1
kind: Sandbox
metadata:
  name: ${SANDBOX_NAME}
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: sandboxd-interop
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: sandboxd
        image: {image_prefix}sandboxd:{image_tag}
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8080
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8080
`;

function getImageTag(): string {
  return process.env.IMAGE_TAG ?? "latest";
}

function getImagePrefix(): string {
  return process.env.IMAGE_PREFIX ?? "kind.local/";
}

interface PodPortForward {
  localPort: number;
  close(): Promise<void>;
}

/**
 * Bridges one local TCP listener to one pod port with client-node's standard
 * PortForward helper. This is intentionally only enough for the small interop
 * call below; the production PodTunnel does not reuse this implementation.
 */
async function openPodPortForward(
  kubeConfig: k8s.KubeConfig,
  namespace: string,
  podName: string,
  targetPort: number,
): Promise<PodPortForward> {
  const sockets = new Set<net.Socket>();
  const websockets = new Set<{ terminate(): void }>();
  const portForward = new k8s.PortForward(kubeConfig);
  let closed = false;

  return new Promise<PodPortForward>((resolve, reject) => {
    const server = net.createServer((socket) => {
      sockets.add(socket);
      let websocket: { terminate(): void } | undefined;
      socket.on("close", () => {
        sockets.delete(socket);
        websocket?.terminate();
      });
      socket.on("error", () => {
        // The port-forward promise reports connection failures. A socket
        // listener is still required so ECONNRESET does not crash the test.
      });

      const errorSink = new Writable({
        write(chunk, _encoding, callback) {
          if (chunk.length > 0) {
            socket.destroy(
              new Error(
                `port-forward to :${targetPort} failed: ${chunk.toString("utf-8")}`,
              ),
            );
          }
          callback();
        },
      });

      portForward
        .portForward(
          namespace,
          podName,
          [targetPort],
          socket,
          errorSink,
          socket,
        )
        .then((result) => {
          websocket =
            typeof result === "function" ? (result() ?? undefined) : result;
          if (!websocket) {
            socket.destroy(
              new Error("port-forward did not return a WebSocket"),
            );
            return;
          }
          if (closed || socket.destroyed) {
            websocket.terminate();
            socket.destroy();
            return;
          }
          websockets.add(websocket);
        })
        .catch((e: unknown) => {
          socket.destroy(e instanceof Error ? e : new Error(String(e)));
        });
    });

    server.on("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const addr = server.address();
      if (!addr || typeof addr === "string") {
        reject(new Error("failed to bind local port-forward listener"));
        return;
      }
      resolve({
        localPort: addr.port,
        close: () =>
          new Promise<void>((res) => {
            closed = true;
            for (const w of websockets) w.terminate();
            for (const s of sockets) s.destroy();
            server.close(() => res());
          }),
      });
    });
  });
}

/**
 * Polls GET /v1/health until it succeeds. The Sandbox/Pod Ready condition
 * only guarantees the kubelet readiness probe passed, not that a fresh
 * port-forward dial against the same pod will immediately succeed.
 */
async function waitForHealthy(
  localPort: number,
  attempts = 20,
  intervalMs = 250,
): Promise<void> {
  let lastError: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      // Each attempt gets its own deadline: without it, a connection that
      // hangs after being accepted (rather than failing outright) would
      // never let the attempts loop above run its course.
      const resp = await fetch(`http://127.0.0.1:${localPort}/v1/health`, {
        signal: AbortSignal.timeout(intervalMs * 4),
      });
      if (resp.ok) return;
      lastError = new Error(`/v1/health returned ${resp.status}`);
    } catch (e) {
      lastError = e;
    }
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  throw new Error(
    `sandboxd did not become healthy over the port-forward: ${String(lastError)}`,
  );
}

describe("TypeScript SDK E2E — sandboxd interop smoke test", () => {
  let tc: TestContext;
  let namespace: string;

  beforeAll(() => {
    tc = new TestContext();
  });

  beforeEach(async () => {
    namespace = await tc.createTempNamespace("ts-sdk-sandboxd-");
  });

  afterEach(async () => {
    await tc.deleteNamespace(namespace);
  });

  test("real gRPC Execute over h2c through a WebSocket pod port-forward", async () => {
    const manifest = SANDBOXD_MANIFEST.replaceAll(
      "{image_prefix}",
      getImagePrefix(),
    ).replaceAll("{image_tag}", getImageTag());
    tc.applyManifestText(manifest, namespace);

    await tc.waitForObject(
      `/apis/agents.x-k8s.io/v1beta1/namespaces/${namespace}/sandboxes`,
      SANDBOX_NAME,
      namespace,
      readyConditionIsTrue(),
    );
    // The Sandbox controller names the backing Pod after the Sandbox.
    await tc.waitForObject(
      `/api/v1/namespaces/${namespace}/pods`,
      SANDBOX_NAME,
      namespace,
      readyConditionIsTrue(),
    );

    const tunnels: PodPortForward[] = [];

    try {
      const restTunnel = await openPodPortForward(
        tc.kubeConfig,
        namespace,
        SANDBOX_NAME,
        8080,
      );
      tunnels.push(restTunnel);

      const grpcTunnel = await openPodPortForward(
        tc.kubeConfig,
        namespace,
        SANDBOX_NAME,
        9090,
      );
      tunnels.push(grpcTunnel);

      // Confirms both port-forwards actually work before spending the real
      // assertion on the gRPC call.
      await waitForHealthy(restTunnel.localPort);

      // createGrpcTransport() always speaks gRPC over HTTP/2 (cleartext
      // h2c against a plain "http://" baseUrl), so there is no httpVersion
      // option to set here — unlike createConnectTransport(), which can
      // negotiate HTTP/1.1.
      const transport = createGrpcTransport({
        baseUrl: `http://127.0.0.1:${grpcTunnel.localPort}`,
        // Parity with grpc-go/grpc-python's 4 MiB receive default; sandboxd
        // buffers Execute's stdout/stderr unboundedly server-side, and
        // Connect-ES's own default is ~4 GiB.
        readMaxBytes: 4 * 1024 * 1024,
      });
      const client = createClient(ProcessService, transport);

      const resp = await client.execute(
        create(ExecuteRequestSchema, {
          config: create(ProcessConfigSchema, {
            command: ["/bin/sh", "-c", "echo hello world"],
          }),
        }),
        // Without a deadline, a stuck call would hang past vitest's own
        // test timeout without ever reaching the finally block below, so
        // the tunnels it holds open would leak into the next test.
        { timeoutMs: 30_000 },
      );

      expect(resp.exitCode).toBe(0);
      expect(new TextDecoder().decode(resp.stdout)).toBe("hello world\n");
      expect(new TextDecoder().decode(resp.stderr)).toBe("");
    } finally {
      await Promise.allSettled(tunnels.map((tunnel) => tunnel.close()));
    }
  });
});
